import type {
  Achievement,
  Assessment,
  ContentSource,
  Course,
  EducationalBackground,
  Exercise,
  ImportLog,
  LearningActivity,
  LearningModule,
  LearningPath,
  Lesson,
  ModuleProject,
  PortfolioProject,
  ProfessionalExperience,
  TechnologySource,
  UserCertificateRecord,
  UserEvent,
  UserProfile,
  UserProject,
  UserTechnologyRecord,
  YouTubePlaylist,
} from './types'

export const mockUser: UserProfile = {
  id: 'user-1',
  name: 'William',
  email: 'william@devpath.ai',
  createdAt: '2025-01-12T10:00:00Z',
  bio: 'Desenvolvedor em formação contínua, focado em JavaScript moderno, React, Node.js e IA aplicada ao desenvolvimento.',
  github: 'williamdev',
  linkedin: 'william-dev',
  desiredRole: 'Desenvolvedor Full Stack Júnior',
  cpf: '123.456.789-00',
  birthDate: '1998-05-15',
  locationType: 'brasil',
  phone: '(11) 98765-4321',
  commercialPhone: '(11) 3456-7890',
  cep: '01310-100',
  socialLinks: {
    linkedin: 'https://linkedin.com/in/william-dev',
    github: 'https://github.com/williamdev',
    facebook: 'https://facebook.com/william.dev',
    instagram: 'https://instagram.com/william.code',
    pinterest: 'https://pinterest.com/williamdev',
    youtube: 'https://youtube.com/@williamcode',
    twitter: 'https://x.com/william_dev',
    blog: 'https://williamdev.io',
  },
  notificationPreferences: {
    newPrograms: true,
    contentUpdates: true,
    activitiesDeadlines: true,
    aiFeedback: true,
  },
  onboarded: true,
  placementDone: true,
}

export const mockPath: LearningPath = {
  id: 'path-fsjs',
  title: 'Full Stack JavaScript & Fundamentos',
  goal: 'Tornar-se desenvolvedor de software profissional',
  area: 'fullstack',
  description:
    'Trilha completa e sequencial de programação com cursos oficiais e videoaulas 100% reais, exercícios práticos e avaliações.',
  moduleIds: ['mod-logica', 'mod-html', 'mod-js'],
}

export const defaultContentSources: ContentSource[] = [
  {
    id: 'src-curso-em-video',
    name: 'Curso em Vídeo (Gustavo Guanabara)',
    sourceType: 'youtube_channel',
    channelId: 'UCrWvhVmt0Qac3HgsjQK62FQ',
    channelUrl: 'https://www.youtube.com/@CursoemVideo',
    handle: '@CursoemVideo',
    description: 'Canal de referência absoluta em ensino de fundamentos, algoritmos, lógica de programação, HTML/CSS, JavaScript e Banco de Dados.',
    priority: 100,
    isTrusted: true,
    isActive: true,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
]

export const mockModules: LearningModule[] = []

export const defaultOfficialModules: LearningModule[] = [
  {
    id: 'mod-logica',
    order: 1,
    phase: 'Fundamentos da Programação',
    phaseOrder: 1,
    title: 'Lógica de Programação & Algoritmos',
    technology: 'Lógica & Algoritmos',
    description: 'Aprenda a pensar como um programador: algoritmos, raciocínio lógico, variáveis, estruturas de controle, repetições, vetores e matrizes.',
    objective: 'Dominar os fundamentos universais do raciocínio computacional antes de qualquer linguagem com o curso completo de 17 aulas.',
    icon: 'brain',
    prerequisites: [],
    lessonIds: [
      'l-logica-1',
      'l-logica-2',
      'l-logica-3',
      'l-logica-4',
      'l-logica-5',
      'l-logica-6',
      'l-logica-7',
      'l-logica-8',
      'l-logica-9',
      'l-logica-10',
      'l-logica-11',
      'l-logica-12',
      'l-logica-13',
      'l-logica-14',
      'l-logica-15',
      'l-logica-16',
      'l-logica-17',
    ],
    exerciseCount: 17,
    hasProject: true,
    hasAssessment: true,
    estimatedHours: 12,
    skills: ['Lógica de Programação', 'Algoritmos', 'Visualg', 'Pseudocódigo', 'Condicionais', 'Loops', 'Procedimentos', 'Funções', 'Vetores', 'Matrizes'],
    courseId: 'crs-logica',
  },
  {
    id: 'mod-html',
    order: 2,
    phase: 'Web Front-end',
    phaseOrder: 2,
    title: 'HTML5 Semântico & Estruturação Web',
    technology: 'HTML5 & CSS3',
    description: 'Estruturação de documentos modernos, semântica, SEO, acessibilidade, links, parágrafos, listas e imagens.',
    objective: 'Criar estruturas de páginas web modernas e acessíveis com 10 aulas oficiais completas.',
    icon: 'layout',
    prerequisites: ['mod-logica'],
    lessonIds: [
      'l-html-1',
      'l-html-2',
      'l-html-3',
      'l-html-4',
      'l-html-5',
      'l-html-6',
      'l-html-7',
      'l-html-8',
      'l-html-9',
      'l-html-10',
    ],
    exerciseCount: 10,
    hasProject: true,
    hasAssessment: true,
    estimatedHours: 10,
    skills: ['HTML5', 'Semântica', 'SEO', 'Acessibilidade', 'Formulários', 'Links & Mídias'],
    courseId: 'crs-html',
  },
  {
    id: 'mod-js',
    order: 3,
    phase: 'Linguagem Principal',
    phaseOrder: 3,
    title: 'JavaScript Moderno (ES6+) & DOM',
    technology: 'JavaScript',
    description: 'A linguagem da web: tipos primitivos, variáveis, operadores, DOM, eventos, condições, laços e funções.',
    objective: 'Programar o comportamento dinâmico de aplicações client-side com 14 aulas reais completas do curso oficial.',
    icon: 'code-2',
    prerequisites: ['mod-html'],
    lessonIds: [
      'l-js-1',
      'l-js-2',
      'l-js-3',
      'l-js-4',
      'l-js-5',
      'l-js-6',
      'l-js-7',
      'l-js-8',
      'l-js-9',
      'l-js-10',
      'l-js-11',
      'l-js-12',
      'l-js-13',
      'l-js-14',
    ],
    exerciseCount: 14,
    hasProject: true,
    hasAssessment: true,
    estimatedHours: 18,
    skills: ['JavaScript', 'ES6+', 'DOM', 'Eventos', 'Condicionais', 'Loops', 'Funções', 'Template Strings'],
    courseId: 'crs-js',
  },
]

/**
 * Authentic, 100% verified YouTube lessons mapped 1-to-1 to complete original playlists.
 */
const rawLessons: Lesson[] = [
  // --- Módulo 1: Lógica de Programação (Curso em Vídeo - 17 Aulas Reais e Verificadas) ---
  {
    id: 'l-logica-1',
    moduleId: 'mod-logica',
    order: 1,
    title: 'Curso de Algoritmos #01 - Introdução a Algoritmos',
    type: 'video',
    durationMin: 28,
    description: 'Aula fundamental: entenda o que é um algoritmo, passos lógicos e o raciocínio por trás de todo programa de computador.',
    videoId: '8mei6uVttho',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV',
    technology: 'Lógica & Algoritmos',
    topic: 'Introdução a Algoritmos',
    thumbnailUrl: 'https://img.youtube.com/vi/8mei6uVttho/hqdefault.jpg',
  },
  {
    id: 'l-logica-2',
    moduleId: 'mod-logica',
    order: 2,
    title: 'Curso de Algoritmos #02 - Primeiro Algoritmo no Visualg',
    type: 'video',
    durationMin: 26,
    description: 'Como declarar variáveis na memória, tipos primitivos e execução passo a passo no Visualg.',
    videoId: 'M2Af7gkbbro',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV',
    technology: 'Lógica & Algoritmos',
    topic: 'Variáveis e Memória',
    thumbnailUrl: 'https://img.youtube.com/vi/M2Af7gkbbro/hqdefault.jpg',
  },
  {
    id: 'l-logica-3',
    moduleId: 'mod-logica',
    order: 3,
    title: 'Curso de Algoritmos #03 - Comando de Entrada e Operadores',
    type: 'video',
    durationMin: 25,
    description: 'Recebendo dados do usuário e realizando cálculos matemáticos dentro do algoritmo.',
    videoId: 'RDrfZ-7WE8c',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV',
    technology: 'Lógica & Algoritmos',
    topic: 'Entrada e Saída',
    thumbnailUrl: 'https://img.youtube.com/vi/RDrfZ-7WE8c/hqdefault.jpg',
  },
  {
    id: 'l-logica-4',
    moduleId: 'mod-logica',
    order: 4,
    title: 'Curso de Algoritmos #04 - Operadores Lógicos e Relacionais',
    type: 'video',
    durationMin: 31,
    description: 'Comparações de maior, menor, igual e operadores lógicos E, OU e NÃO para decisões.',
    videoId: 'U_A2kwUfmlw',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV',
    technology: 'Lógica & Algoritmos',
    topic: 'Operadores Lógicos',
    thumbnailUrl: 'https://img.youtube.com/vi/U_A2kwUfmlw/hqdefault.jpg',
  },
  {
    id: 'l-logica-5',
    moduleId: 'mod-logica',
    order: 5,
    title: 'Curso de Algoritmos #05 - Exercícios de Algoritmos Resolvidos (Parte 1)',
    type: 'video',
    durationMin: 35,
    description: 'Resolução passo a passo de exercícios práticos com operadores e variáveis.',
    videoId: 'Ig4QZNpVZYs',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV',
    technology: 'Lógica & Algoritmos',
    topic: 'Exercícios Práticos',
    thumbnailUrl: 'https://img.youtube.com/vi/Ig4QZNpVZYs/hqdefault.jpg',
  },
  {
    id: 'l-logica-6',
    moduleId: 'mod-logica',
    order: 6,
    title: 'Curso de Algoritmos #06 - Exercícios Práticos de Algoritmos (Parte 2)',
    type: 'video',
    durationMin: 28,
    description: 'Fixação de raciocínio lógico com problemas aplicados de cálculo e entrada/saída.',
    videoId: 'GrPkuk1ezyo',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV',
    technology: 'Lógica & Algoritmos',
    topic: 'Exercícios Práticos',
    thumbnailUrl: 'https://img.youtube.com/vi/GrPkuk1ezyo/hqdefault.jpg',
  },
  {
    id: 'l-logica-7',
    moduleId: 'mod-logica',
    order: 7,
    title: 'Curso de Algoritmos #07 - Estruturas Condicionais 1 (SE / ENTÃO / SENÃO)',
    type: 'video',
    durationMin: 29,
    description: 'Desvios condicionais simples e compostos no fluxo de execução do algoritmo.',
    videoId: 'v2nCgGSVCeE',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV',
    technology: 'Lógica & Algoritmos',
    topic: 'Estruturas Condicionais',
    thumbnailUrl: 'https://img.youtube.com/vi/v2nCgGSVCeE/hqdefault.jpg',
  },
  {
    id: 'l-logica-8',
    moduleId: 'mod-logica',
    order: 8,
    title: 'Curso de Algoritmos #08 - Estruturas Condicionais 2 (ESCOLHA / CASO)',
    type: 'video',
    durationMin: 30,
    description: 'Estruturas de seleção múltipla com escolha-caso para múltiplos caminhos.',
    videoId: '_g05aHdBAEY',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV',
    technology: 'Lógica & Algoritmos',
    topic: 'Seleção Múltipla',
    thumbnailUrl: 'https://img.youtube.com/vi/_g05aHdBAEY/hqdefault.jpg',
  },
  {
    id: 'l-logica-9',
    moduleId: 'mod-logica',
    order: 9,
    title: 'Curso de Algoritmos #09 - Estruturas de Repetição 1 (ENQUANTO / FAÇA)',
    type: 'video',
    durationMin: 32,
    description: 'Automatize processos e aprenda o funcionamento de laços com teste no início.',
    videoId: '7gGFHzqh4d8',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV',
    technology: 'Lógica & Algoritmos',
    topic: 'Laço Enquanto',
    thumbnailUrl: 'https://img.youtube.com/vi/7gGFHzqh4d8/hqdefault.jpg',
  },
  {
    id: 'l-logica-10',
    moduleId: 'mod-logica',
    order: 10,
    title: 'Curso de Algoritmos #10 - Estruturas de Repetição 2 (REPITA / ATÉ)',
    type: 'video',
    durationMin: 27,
    description: 'Laços de repetição com teste no final e validação de dados de entrada.',
    videoId: 'U5PnCt58Q68',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV',
    technology: 'Lógica & Algoritmos',
    topic: 'Laço Repita',
    thumbnailUrl: 'https://img.youtube.com/vi/U5PnCt58Q68/hqdefault.jpg',
  },
  {
    id: 'l-logica-11',
    moduleId: 'mod-logica',
    order: 11,
    title: 'Curso de Algoritmos #11 - Estruturas de Repetição 3 (PARA / DE / ATÉ / PASSO)',
    type: 'video',
    durationMin: 33,
    description: 'Controle de iterações com variável de controle e laços determinados.',
    videoId: 'fP49L1i_-HU',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV',
    technology: 'Lógica & Algoritmos',
    topic: 'Laço Para',
    thumbnailUrl: 'https://img.youtube.com/vi/fP49L1i_-HU/hqdefault.jpg',
  },
  {
    id: 'l-logica-12',
    moduleId: 'mod-logica',
    order: 12,
    title: 'Curso de Algoritmos #12 - Procedimentos (Rotinas e Passagem de Parâmetros)',
    type: 'video',
    durationMin: 30,
    description: 'Modularização de código: como criar procedimentos e reutilizar rotinas.',
    videoId: 'WJQz20i7CyI',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV',
    technology: 'Lógica & Algoritmos',
    topic: 'Procedimentos',
    thumbnailUrl: 'https://img.youtube.com/vi/WJQz20i7CyI/hqdefault.jpg',
  },
  {
    id: 'l-logica-13',
    moduleId: 'mod-logica',
    order: 13,
    title: 'Curso de Algoritmos #13 - Funções (Retorno de Valores)',
    type: 'video',
    durationMin: 26,
    description: 'Diferença entre procedimentos e funções com retorno de valor computado.',
    videoId: 'KoNehy7rn8U',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV',
    technology: 'Lógica & Algoritmos',
    topic: 'Funções',
    thumbnailUrl: 'https://img.youtube.com/vi/KoNehy7rn8U/hqdefault.jpg',
  },
  {
    id: 'l-logica-14',
    moduleId: 'mod-logica',
    order: 14,
    title: 'Curso de Algoritmos #14 - Vetores (Variáveis Compostas Unidimensionais)',
    type: 'video',
    durationMin: 34,
    description: 'Armazenando múltiplos valores em índices contínuos na memória.',
    videoId: '-nNx7e8GzHQ',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV',
    technology: 'Lógica & Algoritmos',
    topic: 'Vetores',
    thumbnailUrl: 'https://img.youtube.com/vi/-nNx7e8GzHQ/hqdefault.jpg',
  },
  {
    id: 'l-logica-15',
    moduleId: 'mod-logica',
    order: 15,
    title: 'Curso de Algoritmos #15 - Matrizes (Variáveis Compostas Bidimensionais)',
    type: 'video',
    durationMin: 36,
    description: 'Tabelas, linhas e colunas de dados indexados no computador.',
    videoId: 'j9473xQ39vY',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV',
    technology: 'Lógica & Algoritmos',
    topic: 'Matrizes',
    thumbnailUrl: 'https://img.youtube.com/vi/j9473xQ39vY/hqdefault.jpg',
  },
  {
    id: 'l-logica-16',
    moduleId: 'mod-logica',
    order: 16,
    title: 'Curso de Algoritmos #16 - Exercícios Práticos de Matrizes',
    type: 'video',
    durationMin: 40,
    description: 'Desafios completos com matrizes de identidade, diagonais e tabuleiros.',
    videoId: 'hkE9WrjpAAk',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV',
    technology: 'Lógica & Algoritmos',
    topic: 'Exercícios com Matrizes',
    thumbnailUrl: 'https://img.youtube.com/vi/hkE9WrjpAAk/hqdefault.jpg',
  },
  {
    id: 'l-logica-17',
    moduleId: 'mod-logica',
    order: 17,
    title: 'Curso de Algoritmos #17 - Encerramento e Próximos Passos na Programação',
    type: 'video',
    durationMin: 22,
    description: 'Como transicionar da lógica pura para linguagens reais (JavaScript, Python, C#).',
    videoId: 'uZImRLpJunA',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV',
    technology: 'Lógica & Algoritmos',
    topic: 'Próximos Passos',
    thumbnailUrl: 'https://img.youtube.com/vi/uZImRLpJunA/hqdefault.jpg',
  },

  // --- Módulo 2: HTML5 Semântico (Curso em Vídeo - 10 Aulas Reais e Verificadas) ---
  {
    id: 'l-html-1',
    moduleId: 'mod-html',
    order: 1,
    title: 'Curso HTML5 e CSS3 #01 - Introdução e Visão Geral',
    type: 'video',
    durationMin: 30,
    description: 'A anatomia de um documento web com a declaração doctype, head, body e a estrutura fundamental do HTML5.',
    videoId: 'epDCjksKMok',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlAnJ_jJtV29RFxnPHDuk9o',
    technology: 'HTML5 & CSS3',
    topic: 'Semântica Web',
    thumbnailUrl: 'https://img.youtube.com/vi/epDCjksKMok/hqdefault.jpg',
  },
  {
    id: 'l-html-2',
    moduleId: 'mod-html',
    order: 2,
    title: 'Curso HTML5 e CSS3 #02 - Como a Internet Funciona?',
    type: 'video',
    durationMin: 26,
    description: 'Servidores, clientes, protocolo HTTP e como navegadores interpretam códigos HTML.',
    videoId: 'rsFCVjr5yxc',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlAnJ_jJtV29RFxnPHDuk9o',
    technology: 'HTML5 & CSS3',
    topic: 'Fundamentos da Web',
    thumbnailUrl: 'https://img.youtube.com/vi/rsFCVjr5yxc/hqdefault.jpg',
  },
  {
    id: 'l-html-3',
    moduleId: 'mod-html',
    order: 3,
    title: 'Curso HTML5 e CSS3 #03 - Como a Web Funciona? DNS e Requisições',
    type: 'video',
    durationMin: 28,
    description: 'Endereçamento IP, DNS, portas de conexão e o ciclo de vida de uma requisição web.',
    videoId: 'NSmapCNcSyI',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlAnJ_jJtV29RFxnPHDuk9o',
    technology: 'HTML5 & CSS3',
    topic: 'DNS e Protocolos',
    thumbnailUrl: 'https://img.youtube.com/vi/NSmapCNcSyI/hqdefault.jpg',
  },
  {
    id: 'l-html-4',
    moduleId: 'mod-html',
    order: 4,
    title: 'Curso HTML5 e CSS3 #04 - Seu Primeiro Código HTML5',
    type: 'video',
    durationMin: 32,
    description: 'Criando seu primeiro arquivo index.html, títulos h1 a h6 e visualizando no navegador.',
    videoId: 'LMfeZ6XD0No',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlAnJ_jJtV29RFxnPHDuk9o',
    technology: 'HTML5 & CSS3',
    topic: 'Primeiro Código',
    thumbnailUrl: 'https://img.youtube.com/vi/LMfeZ6XD0No/hqdefault.jpg',
  },
  {
    id: 'l-html-5',
    moduleId: 'mod-html',
    order: 5,
    title: 'Curso HTML5 e CSS3 #05 - Parágrafos, Quebras de Linha e Símbolos',
    type: 'video',
    durationMin: 27,
    description: 'Tags de parágrafo p, quebras de linha br, entidades especiais de caracteres e símbolos.',
    videoId: 'U_A2kwUfmlw',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlAnJ_jJtV29RFxnPHDuk9o',
    technology: 'HTML5 & CSS3',
    topic: 'Parágrafos e Símbolos',
    thumbnailUrl: 'https://img.youtube.com/vi/U_A2kwUfmlw/hqdefault.jpg',
  },
  {
    id: 'l-html-6',
    moduleId: 'mod-html',
    order: 6,
    title: 'Curso HTML5 e CSS3 #06 - Inserindo Imagens e Formatos de Mídia',
    type: 'video',
    durationMin: 30,
    description: 'Como carregar imagens com tag img, atributos src, alt para acessibilidade e formatos WebP/PNG/JPG.',
    videoId: 'yCSSsBNBzso',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlAnJ_jJtV29RFxnPHDuk9o',
    technology: 'HTML5 & CSS3',
    topic: 'Imagens e Acessibilidade',
    thumbnailUrl: 'https://img.youtube.com/vi/yCSSsBNBzso/hqdefault.jpg',
  },
  {
    id: 'l-html-7',
    moduleId: 'mod-html',
    order: 7,
    title: 'Curso HTML5 e CSS3 #07 - Formatação Semântica de Textos',
    type: 'video',
    durationMin: 29,
    description: 'Diferença entre formatação visual (b, i) e formatação semântica moderna (strong, em, mark).',
    videoId: 'P8LxrpNQrTU',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlAnJ_jJtV29RFxnPHDuk9o',
    technology: 'HTML5 & CSS3',
    topic: 'Formatação de Texto',
    thumbnailUrl: 'https://img.youtube.com/vi/P8LxrpNQrTU/hqdefault.jpg',
  },
  {
    id: 'l-html-8',
    moduleId: 'mod-html',
    order: 8,
    title: 'Curso HTML5 e CSS3 #08 - Citações, Códigos e Abreviações',
    type: 'video',
    durationMin: 25,
    description: 'Tags semânticas quote, blockquote, code, pre e abbr para código legível por mecanismos de busca.',
    videoId: 'EANOXuQsglo',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlAnJ_jJtV29RFxnPHDuk9o',
    technology: 'HTML5 & CSS3',
    topic: 'Citações e Código',
    thumbnailUrl: 'https://img.youtube.com/vi/EANOXuQsglo/hqdefault.jpg',
  },
  {
    id: 'l-html-9',
    moduleId: 'mod-html',
    order: 9,
    title: 'Curso HTML5 e CSS3 #09 - Listas Ordenadas, Não-Ordenadas e de Definição',
    type: 'video',
    durationMin: 31,
    description: 'Construção de listas com ol, ul, li e listas descritivas dl, dt, dd.',
    videoId: 'wlgU9ltZwqc',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlAnJ_jJtV29RFxnPHDuk9o',
    technology: 'HTML5 & CSS3',
    topic: 'Listas em HTML',
    thumbnailUrl: 'https://img.youtube.com/vi/wlgU9ltZwqc/hqdefault.jpg',
  },
  {
    id: 'l-html-10',
    moduleId: 'mod-html',
    order: 10,
    title: 'Curso HTML5 e CSS3 #10 - Links Internos, Externos e Downloads',
    type: 'video',
    durationMin: 34,
    description: 'Navegação web com a tag anchor (a), atributos href, target=_blank, download e âncoras na mesma página.',
    videoId: 'oQExPqFT7ec',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlAnJ_jJtV29RFxnPHDuk9o',
    technology: 'HTML5 & CSS3',
    topic: 'Links e Navegação',
    thumbnailUrl: 'https://img.youtube.com/vi/oQExPqFT7ec/hqdefault.jpg',
  },

  // --- Módulo 3: JavaScript Moderno (Curso em Vídeo - 14 Aulas Reais e Verificadas) ---
  {
    id: 'l-js-1',
    moduleId: 'mod-js',
    order: 1,
    title: 'Curso JavaScript #01 - O que o JavaScript é capaz de fazer?',
    type: 'video',
    durationMin: 28,
    description: 'Visão geral da linguagem mais usada no mundo: de scripts no navegador a servidores e inteligência artificial.',
    videoId: '1-w1RfGIov4',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlsK3Nr9GVvXCbpQyHQl1o1',
    technology: 'JavaScript',
    topic: 'Introdução ao JavaScript',
    thumbnailUrl: 'https://img.youtube.com/vi/1-w1RfGIov4/hqdefault.jpg',
  },
  {
    id: 'l-js-2',
    moduleId: 'mod-js',
    order: 2,
    title: 'Curso JavaScript #02 - Para que serve o JavaScript e onde executa?',
    type: 'video',
    durationMin: 25,
    description: 'A história do JS, engines como V8, a relação com ECMAScript e sua evolução.',
    videoId: 'BXqUH86F-kA',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlsK3Nr9GVvXCbpQyHQl1o1',
    technology: 'JavaScript',
    topic: 'História e Engines',
    thumbnailUrl: 'https://img.youtube.com/vi/BXqUH86F-kA/hqdefault.jpg',
  },
  {
    id: 'l-js-3',
    moduleId: 'mod-js',
    order: 3,
    title: 'Curso JavaScript #03 - Dando os Primeiros Passos no Navegador',
    type: 'video',
    durationMin: 27,
    description: 'Comandos de alerta window.alert, window.confirm e window.prompt para interação inicial.',
    videoId: 'uzEhd3Lugik',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlsK3Nr9GVvXCbpQyHQl1o1',
    technology: 'JavaScript',
    topic: 'Primeiros Passos',
    thumbnailUrl: 'https://img.youtube.com/vi/uzEhd3Lugik/hqdefault.jpg',
  },
  {
    id: 'l-js-4',
    moduleId: 'mod-js',
    order: 4,
    title: 'Curso JavaScript #04 - Criando o seu Primeiro Script',
    type: 'video',
    durationMin: 26,
    description: 'Estruturação de scripts internos com tag script e scripts externos vinculados a arquivos .js.',
    videoId: 'Ptbk2af68e8',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlsK3Nr9GVvXCbpQyHQl1o1',
    technology: 'JavaScript',
    topic: 'Estrutura de Script',
    thumbnailUrl: 'https://img.youtube.com/vi/Ptbk2af68e8/hqdefault.jpg',
  },
  {
    id: 'l-js-5',
    moduleId: 'mod-js',
    order: 5,
    title: 'Curso JavaScript #05 - Variáveis e Tipos Primitivos (let, const, number, string)',
    type: 'video',
    durationMin: 32,
    description: 'Declaração de variáveis na memória, tipos de dados primitivos e o operador typeof.',
    videoId: 'rUTKomc2gG8',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlsK3Nr9GVvXCbpQyHQl1o1',
    technology: 'JavaScript',
    topic: 'Variáveis e Tipos',
    thumbnailUrl: 'https://img.youtube.com/vi/rUTKomc2gG8/hqdefault.jpg',
  },
  {
    id: 'l-js-6',
    moduleId: 'mod-js',
    order: 6,
    title: 'Curso JavaScript #06 - Tratamento de Dados e Template Strings',
    type: 'video',
    durationMin: 30,
    description: 'Conversão de tipos (Number.parseInt, Number.parseFloat, String), concatenação e interpolação moderna com backticks.',
    videoId: 'FdePtO5JSd0',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlsK3Nr9GVvXCbpQyHQl1o1',
    technology: 'JavaScript',
    topic: 'Template Strings',
    thumbnailUrl: 'https://img.youtube.com/vi/FdePtO5JSd0/hqdefault.jpg',
  },
  {
    id: 'l-js-7',
    moduleId: 'mod-js',
    order: 7,
    title: 'Curso JavaScript #07 - Operadores Aritméticos e de Atribuição',
    type: 'video',
    durationMin: 33,
    description: 'Soma, subtração, multiplicação, divisão, módulo, exponenciação e auto-atribuição no JavaScript.',
    videoId: 'OmmJBfcMJA8',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlsK3Nr9GVvXCbpQyHQl1o1',
    technology: 'JavaScript',
    topic: 'Operadores Aritméticos',
    thumbnailUrl: 'https://img.youtube.com/vi/OmmJBfcMJA8/hqdefault.jpg',
  },
  {
    id: 'l-js-8',
    moduleId: 'mod-js',
    order: 8,
    title: 'Curso JavaScript #08 - Operadores Relacionais, Lógicos e Ternário',
    type: 'video',
    durationMin: 35,
    description: 'Comparações de igualdade estrita (===), operadores lógicos (&&, ||, !) e o operador ternário (?:).',
    videoId: 'FjT97HVT5g8',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlsK3Nr9GVvXCbpQyHQl1o1',
    technology: 'JavaScript',
    topic: 'Operadores Lógicos e Ternário',
    thumbnailUrl: 'https://img.youtube.com/vi/FjT97HVT5g8/hqdefault.jpg',
  },
  {
    id: 'l-js-9',
    moduleId: 'mod-js',
    order: 9,
    title: 'Curso JavaScript #09 - Introdução ao DOM (Document Object Model)',
    type: 'video',
    durationMin: 34,
    description: 'A árvore DOM: selecionando elementos HTML por TagName, ID, ClassName e querySelector.',
    videoId: 'Vbabsye7mWo',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlsK3Nr9GVvXCbpQyHQl1o1',
    technology: 'JavaScript',
    topic: 'Árvore DOM',
    thumbnailUrl: 'https://img.youtube.com/vi/Vbabsye7mWo/hqdefault.jpg',
  },
  {
    id: 'l-js-10',
    moduleId: 'mod-js',
    order: 10,
    title: 'Curso JavaScript #10 - Eventos DOM e Funções de Disparo',
    type: 'video',
    durationMin: 36,
    description: 'Ouvindo eventos do mouse e teclado com addEventListener e alterando estilos em tempo real.',
    videoId: 'OJgu_KCCUSY',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlsK3Nr9GVvXCbpQyHQl1o1',
    technology: 'JavaScript',
    topic: 'Eventos DOM',
    thumbnailUrl: 'https://img.youtube.com/vi/OJgu_KCCUSY/hqdefault.jpg',
  },
  {
    id: 'l-js-11',
    moduleId: 'mod-js',
    order: 11,
    title: 'Curso JavaScript #11 - Condições em JavaScript (if / else)',
    type: 'video',
    durationMin: 31,
    description: 'Tomada de decisões com estruturas condicionais simples, compostas e validação de regras de negócio.',
    videoId: 'hZG9ODUdxHo',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlsK3Nr9GVvXCbpQyHQl1o1',
    technology: 'JavaScript',
    topic: 'Condicionais if/else',
    thumbnailUrl: 'https://img.youtube.com/vi/hZG9ODUdxHo/hqdefault.jpg',
  },
  {
    id: 'l-js-12',
    moduleId: 'mod-js',
    order: 12,
    title: 'Curso JavaScript #12 - Condições Aninhadas e Múltiplas (switch / case)',
    type: 'video',
    durationMin: 33,
    description: 'Condições aninhadas para horas do dia, voto obrigatório e seleção múltipla com switch case.',
    videoId: 'BP63NhITvao',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlsK3Nr9GVvXCbpQyHQl1o1',
    technology: 'JavaScript',
    topic: 'Switch Case',
    thumbnailUrl: 'https://img.youtube.com/vi/BP63NhITvao/hqdefault.jpg',
  },
  {
    id: 'l-js-13',
    moduleId: 'mod-js',
    order: 13,
    title: 'Curso JavaScript #13 - Estruturas de Repetição (while / do while)',
    type: 'video',
    durationMin: 30,
    description: 'Laços de repetição com teste no início e no final para automatização de tarefas.',
    videoId: '5rZqYPKIwkY',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlsK3Nr9GVvXCbpQyHQl1o1',
    technology: 'JavaScript',
    topic: 'Loops while',
    thumbnailUrl: 'https://img.youtube.com/vi/5rZqYPKIwkY/hqdefault.jpg',
  },
  {
    id: 'l-js-14',
    moduleId: 'mod-js',
    order: 14,
    title: 'Curso JavaScript #14 - Funções em JavaScript (Parâmetros e Retorno)',
    type: 'video',
    durationMin: 38,
    description: 'Declaração de funções, passagem de parâmetros formais e reais, retorno de valores e funções reutilizáveis.',
    videoId: 'mc3TKp2XzhI',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlsK3Nr9GVvXCbpQyHQl1o1',
    technology: 'JavaScript',
    topic: 'Funções e Parâmetros',
    thumbnailUrl: 'https://img.youtube.com/vi/mc3TKp2XzhI/hqdefault.jpg',
  },
]

export const mockLessons: Lesson[] = []

export const defaultOfficialLessons: Lesson[] = rawLessons.map((l) => ({
  ...l,
  externalVideoId: l.externalVideoId || l.videoId,
  videoUrl: l.videoUrl || (l.videoId ? `https://www.youtube.com/watch?v=${l.videoId}` : undefined),
  sourceType: l.sourceType || (l.type === 'video' ? 'youtube' : 'external'),
  availabilityStatus: l.availabilityStatus || 'available',
  youtubeExists: l.youtubeExists ?? true,
  embedAvailable: l.embedAvailable ?? true,
  lastCheckedAt: l.lastCheckedAt || new Date().toISOString(),
}))

export const defaultOfficialCourses: Course[] = [
  {
    id: 'crs-logica',
    title: 'Curso de Algoritmos & Lógica de Programação',
    slug: 'logica-de-programacao-algoritmos',
    description: 'O curso de referência absoluta de Gustavo Guanabara (Curso em Vídeo) para aprender a programar do zero com 17 aulas práticas completas.',
    level: 'iniciante-absoluto',
    technology: 'Lógica & Algoritmos',
    category: 'Fundamentos da Programação',
    thumbnailUrl: 'https://img.youtube.com/vi/8mei6uVttho/hqdefault.jpg',
    status: 'ativo',
    playlistId: 'PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV',
    playlistUrl: 'https://www.youtube.com/playlist?list=PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV',
    channelTitle: 'Curso em Vídeo',
    classificationConfidence: 100,
    prerequisites: [],
    skills: ['Lógica de Programação', 'Algoritmos', 'Visualg', 'Estruturas Condicionais', 'Estruturas de Repetição', 'Procedimentos', 'Funções', 'Vetores', 'Matrizes'],
    modulesCount: 1,
    lessonsCount: 17,
    totalHours: 12,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'crs-html',
    title: 'Curso de HTML5 Semântico & Estruturação Web',
    slug: 'curso-html5-semantico',
    description: 'Construa páginas web semânticas, acessíveis e otimizadas para SEO com 10 aulas completas de HTML5.',
    level: 'iniciante-absoluto',
    technology: 'HTML5 & CSS3',
    category: 'Web & Front-end',
    thumbnailUrl: 'https://img.youtube.com/vi/epDCjksKMok/hqdefault.jpg',
    status: 'ativo',
    playlistId: 'PLHz_AreHm4dlAnJ_jJtV29RFxnPHDuk9o',
    playlistUrl: 'https://www.youtube.com/playlist?list=PLHz_AreHm4dlAnJ_jJtV29RFxnPHDuk9o',
    channelTitle: 'Curso em Vídeo',
    classificationConfidence: 99,
    prerequisites: ['mod-logica'],
    skills: ['HTML5', 'Semântica Web', 'SEO', 'Acessibilidade', 'Formulários', 'Links'],
    modulesCount: 1,
    lessonsCount: 10,
    totalHours: 10,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'crs-js',
    title: 'Curso de JavaScript Moderno (ES6+) & DOM',
    slug: 'curso-javascript-moderno',
    description: 'O curso definitivo de JavaScript por Gustavo Guanabara: variáveis, template strings, operadores, DOM, eventos, loops e funções.',
    level: 'iniciante',
    technology: 'JavaScript',
    category: 'Web & Front-end',
    thumbnailUrl: 'https://img.youtube.com/vi/1-w1RfGIov4/hqdefault.jpg',
    status: 'ativo',
    playlistId: 'PLHz_AreHm4dlsK3Nr9GVvXCbpQyHQl1o1',
    playlistUrl: 'https://www.youtube.com/playlist?list=PLHz_AreHm4dlsK3Nr9GVvXCbpQyHQl1o1',
    channelTitle: 'Curso em Vídeo',
    classificationConfidence: 100,
    prerequisites: ['mod-html'],
    skills: ['JavaScript', 'ES6+', 'DOM', 'Eventos', 'Condicionais', 'Loops', 'Funções'],
    modulesCount: 1,
    lessonsCount: 14,
    totalHours: 18,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
]

export const defaultTechnologySources: TechnologySource[] = [
  {
    id: 'ts-logica',
    technology: 'Lógica de Programação',
    primaryPlaylistId: 'PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV',
    primaryPlaylistUrl: 'https://www.youtube.com/playlist?list=PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV',
    channelTitle: 'Curso em Vídeo',
    status: 'ativo',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'ts-html',
    technology: 'HTML5 & CSS3',
    primaryPlaylistId: 'PLHz_AreHm4dlAnJ_jJtV29RFxnPHDuk9o',
    primaryPlaylistUrl: 'https://www.youtube.com/playlist?list=PLHz_AreHm4dlAnJ_jJtV29RFxnPHDuk9o',
    channelTitle: 'Curso em Vídeo',
    status: 'ativo',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'ts-js',
    technology: 'JavaScript',
    primaryPlaylistId: 'PLHz_AreHm4dlsK3Nr9GVvXCbpQyHQl1o1',
    primaryPlaylistUrl: 'https://www.youtube.com/playlist?list=PLHz_AreHm4dlsK3Nr9GVvXCbpQyHQl1o1',
    channelTitle: 'Curso em Vídeo',
    status: 'ativo',
    updatedAt: '2025-01-01T00:00:00Z',
  },
]

export const defaultLearningActivities: LearningActivity[] = [
  {
    id: 'act-log-01',
    title: 'Definição e Estrutura de um Algoritmo',
    statement: 'Analise os conceitos fundamentais de algoritmos e selecione a alternativa que descreve com precisão as características essenciais de um algoritmo computacional eficiente.',
    objective: 'Compreender os pilares de finitude, clareza e determinação de passos lógicos.',
    type: 'multiple_choice',
    difficulty: 'facil',
    status: 'published',
    xpReward: 20,
    expectedTimeMin: 4,
    courseId: 'crs-logica',
    moduleId: 'mod-logica',
    lessonId: 'l-logica-1',
    skillName: 'Pensamento Computacional & Algoritmos',
    technology: 'Lógica',
    options: [
      'Executar em ordem lógica com passos bem definidos, finitos e não ambíguos.',
      'Utilizar o máximo de memória RAM possível para acelerar o processamento.',
      'Ser escrito exclusivamente em código binário sem estrutura de fluxo.',
      'Não possuir condições de parada para garantir execução ininterrupta.',
    ],
    correctOptionIndex: 0,
    explanation:
      'Um algoritmo é uma sequência finita de passos claros, lógicos e não ambíguos para resolver um problema determinado.',
  },
]

export const defaultCourses: Course[] = []
export const mockProjects: ModuleProject[] = []
export const mockAssessments: Assessment[] = []

export const mockAchievements: Achievement[] = [
  {
    id: 'ach-1',
    title: 'Primeiro Código',
    description: 'Concluiu sua primeira aula no DevPath AI',
    icon: 'zap',
    unlockedAt: '2025-01-12T10:30:00Z',
    xpReward: 50,
  },
  {
    id: 'ach-2',
    title: 'Mestre da Lógica',
    description: 'Concluiu todas as missões de Lógica de Programação',
    icon: 'brain',
    unlockedAt: undefined,
    xpReward: 200,
  },
]

export const placementQuestions = [
  {
    id: 'pq-1',
    question: 'Qual é o resultado da expressão 5 + 3 * 2 em JavaScript?',
    options: ['16', '11', '10', '13'],
    correct: 1,
    category: 'Lógica & Sintaxe',
  },
  {
    id: 'pq-2',
    question: 'Qual palavra-chave declara uma variável imutável em JavaScript moderno?',
    options: ['var', 'let', 'const', 'static'],
    correct: 2,
    category: 'JavaScript Moderno',
  },
  {
    id: 'pq-3',
    question: 'Para que serve a tag semântica <main> no HTML5?',
    options: [
      'Definir o rodapé do documento',
      'Conter o conteúdo principal e exclusivo da página',
      'Criar o menu de navegação',
      'Inserir scripts JavaScript',
    ],
    correct: 1,
    category: 'HTML5 Semântico',
  },
  {
    id: 'pq-4',
    question: 'Em CSS Flexbox, qual propriedade alinha os itens no eixo principal (main axis)?',
    options: ['align-items', 'justify-content', 'align-content', 'flex-direction'],
    correct: 1,
    category: 'CSS & Layout',
  },
  {
    id: 'pq-5',
    question: 'O que é um algoritmo?',
    options: [
      'Um tipo específico de computador quântico',
      'Uma sequência finita de instruções lógicas para resolver um problema',
      'Um banco de dados em nuvem',
      'Uma linguagem de programação binária',
    ],
    correct: 1,
    category: 'Lógica de Programação',
  },
]

export const defaultProfessionalExperiences: ProfessionalExperience[] = []
export const defaultEducationalBackgrounds: EducationalBackground[] = []
export const defaultPortfolioProjects: PortfolioProject[] = []
export const defaultUserEvents: UserEvent[] = []
export const defaultUserCertificates: UserCertificateRecord[] = []
export const defaultUserTechnologies: UserTechnologyRecord[] = []
