import type {
  Achievement,
  Assessment,
  ContentSource,
  Course,
  Exercise,
  ImportLog,
  LearningModule,
  LearningPath,
  Lesson,
  ModuleProject,
  TechnologySource,
  UserProfile,
  UserProject,
  YouTubePlaylist,
} from './types'

export const mockUser: UserProfile = {
  id: 'user-1',
  name: 'William Santos',
  email: 'william@devpath.ai',
  createdAt: '2025-01-12T10:00:00Z',
  bio: 'Em transição de carreira rumo a desenvolvedor Full Stack.',
  github: 'williamdev',
  linkedin: 'william-santos',
  desiredRole: 'Desenvolvedor Full Stack Júnior',
  onboarded: true,
  placementDone: true,
}

export const mockPath: LearningPath = {
  id: 'path-fsjs',
  title: 'Full Stack JavaScript',
  goal: 'Tornar-se desenvolvedor Full Stack',
  area: 'fullstack',
  description:
    'Trilha completa que leva do zero absoluto até a construção e deploy de aplicações completas com JavaScript, React, Node.js e banco de dados.',
  moduleIds: [
    'mod-logica',
    'mod-algoritmos',
    'mod-git',
    'mod-html',
    'mod-css',
    'mod-js',
    'mod-react',
    'mod-node',
    'mod-db',
    'mod-fullstack',
    'mod-carreira',
  ],
}

export const defaultContentSources: ContentSource[] = [
  {
    id: 'src-curso-em-video',
    name: 'Curso em Vídeo (Gustavo Guanabara)',
    sourceType: 'youtube_channel',
    channelId: 'UCrWvhVmt0Qac3HgsjQK62FQ',
    channelUrl: 'https://www.youtube.com/@CursoemVideo',
    handle: '@CursoemVideo',
    description: 'Canal de referência absoluta em ensino de fundamentos, algoritmos, lógica de programação, Python, HTML/CSS, JavaScript e Banco de Dados.',
    priority: 100,
    isTrusted: true,
    isActive: true,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'src-rocketseat',
    name: 'Rocketseat',
    sourceType: 'youtube_channel',
    channelId: 'UCSfwM5u0Nu_0PzSPodbqTWw',
    channelUrl: 'https://www.youtube.com/@rocketseat',
    handle: '@rocketseat',
    description: 'Especialistas no ecossistema JavaScript moderno, React, Node.js e Full Stack.',
    priority: 95,
    isTrusted: true,
    isActive: true,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'src-hora-de-codar',
    name: 'Matheus Battisti - Hora de Codar',
    sourceType: 'youtube_channel',
    channelId: 'UCnLd4Upm_1jO1jK88u4C7_w',
    channelUrl: 'https://www.youtube.com/@MatheusBattisti',
    handle: '@MatheusBattisti',
    description: 'Cursos completos de React, TypeScript, APIs REST e desenvolvimento web prático.',
    priority: 90,
    isTrusted: true,
    isActive: true,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
]

export const mockModules: LearningModule[] = []

export const defaultOfficialModules: LearningModule[] = [
  {
    id: 'mod-logica',
    order: 1,
    phase: 'Fundamentos da Programação',
    phaseOrder: 1,
    title: 'Lógica de Programação & Algoritmos',
    technology: 'Lógica & Algoritmos',
    description: 'Aprenda a pensar como um programador: algoritmos, raciocínio lógico, variáveis, estruturas de controle, repetições, vetores e matrizes.',
    objective: 'Dominar os fundamentos universais do raciocínio computacional antes de qualquer linguagem com o curso completo de 17 aulas.',
    icon: 'brain',
    prerequisites: [],
    lessonIds: [
      'l-logica-1',
      'l-logica-2',
      'l-logica-3',
      'l-logica-4',
      'l-logica-5',
      'l-logica-6',
      'l-logica-7',
      'l-logica-8',
      'l-logica-9',
      'l-logica-10',
      'l-logica-11',
      'l-logica-12',
      'l-logica-13',
      'l-logica-14',
      'l-logica-15',
      'l-logica-16',
      'l-logica-17',
    ],
    exerciseCount: 12,
    hasProject: true,
    hasAssessment: true,
    estimatedHours: 12,
    skills: ['Lógica de Programação', 'Algoritmos', 'Visualg', 'Pseudocódigo', 'Condicionais', 'Loops', 'Procedimentos', 'Funções', 'Vetores', 'Matrizes'],
    courseId: 'crs-logica',
  },
  {
    id: 'mod-algoritmos',
    order: 2,
    phase: 'Fundamentos da Programação',
    phaseOrder: 1,
    title: 'Algoritmos e Estruturas de Dados',
    technology: 'Lógica & Algoritmos',
    description: 'Resolução de problemas estruturados, decomposição, complexidade computacional, filas, pilhas e ordenação.',
    objective: 'Estruturar soluções em algoritmos claros, eficientes e escaláveis.',
    icon: 'workflow',
    prerequisites: ['mod-logica'],
    lessonIds: ['l-algo-1', 'l-algo-2', 'l-algo-3', 'l-algo-4', 'l-algo-5'],
    exerciseCount: 10,
    hasProject: true,
    hasAssessment: true,
    estimatedHours: 8,
    skills: ['Algoritmos', 'Complexidade Big-O', 'Estruturas de dados', 'Pilhas & Filas', 'Busca e Ordenação'],
    courseId: 'crs-algoritmos',
  },
  {
    id: 'mod-git',
    order: 3,
    phase: 'Fundamentos da Programação',
    phaseOrder: 1,
    title: 'Git & GitHub Profissional',
    technology: 'Git & GitHub',
    description: 'Versionamento de código profissional, histórico, branches, pull requests e colaboração remota no GitHub.',
    objective: 'Controlar versões de código e colaborar em repositórios remotos no GitHub.',
    icon: 'git-branch',
    prerequisites: ['mod-algoritmos'],
    lessonIds: ['l-git-1', 'l-git-2', 'l-git-3', 'l-git-4', 'l-git-5', 'l-git-6', 'l-git-7', 'l-git-8'],
    exerciseCount: 8,
    hasProject: false,
    hasAssessment: true,
    estimatedHours: 6,
    skills: ['Git', 'GitHub', 'Commits', 'Branches', 'Pull Requests', 'SSH', 'Merge Conflicts'],
    courseId: 'crs-git',
  },
  {
    id: 'mod-html',
    order: 4,
    phase: 'Web Front-end',
    phaseOrder: 2,
    title: 'HTML5 Semântico & Estruturação Web',
    technology: 'HTML5 & CSS3',
    description: 'Estruturação de documentos modernos, semântica, SEO, acessibilidade, tabelas e formulários.',
    objective: 'Criar estruturas de páginas web modernas e acessíveis.',
    icon: 'layout',
    prerequisites: ['mod-git'],
    lessonIds: [
      'l-html-1',
      'l-html-2',
      'l-html-3',
      'l-html-4',
      'l-html-5',
      'l-html-6',
      'l-html-7',
      'l-html-8',
      'l-html-9',
      'l-html-10',
    ],
    exerciseCount: 10,
    hasProject: true,
    hasAssessment: true,
    estimatedHours: 10,
    skills: ['HTML5', 'Semântica', 'SEO', 'Acessibilidade', 'Formulários', 'Links & Mídias'],
    courseId: 'crs-html',
  },
  {
    id: 'mod-css',
    order: 5,
    phase: 'Web Front-end',
    phaseOrder: 2,
    title: 'CSS3, Flexbox & CSS Grid',
    technology: 'HTML5 & CSS3',
    description: 'Estilização moderna, layouts responsivos, Flexbox, Grid, cores, tipografia e design Mobile-First.',
    objective: 'Construir interfaces visualmente atraentes e totalmente responsivas.',
    icon: 'palette',
    prerequisites: ['mod-html'],
    lessonIds: ['l-css-1', 'l-css-2', 'l-css-3', 'l-css-4', 'l-css-5', 'l-css-6', 'l-css-7', 'l-css-8'],
    exerciseCount: 10,
    hasProject: true,
    hasAssessment: true,
    estimatedHours: 12,
    skills: ['CSS3', 'Box Model', 'Flexbox', 'CSS Grid', 'Responsividade', 'Mobile-First', 'Google Fonts'],
    courseId: 'crs-css',
  },
  {
    id: 'mod-js',
    order: 6,
    phase: 'Linguagem Principal',
    phaseOrder: 3,
    title: 'JavaScript Moderno (ES6+) & DOM',
    technology: 'JavaScript',
    description: 'A linguagem da web: tipos, variáveis, operadores, DOM, eventos, condições, repetições, arrays e funções.',
    objective: 'Programar o comportamento dinâmico de aplicações client-side com todas as 16 aulas do curso oficial.',
    icon: 'code-2',
    prerequisites: ['mod-css'],
    lessonIds: [
      'l-js-1',
      'l-js-2',
      'l-js-3',
      'l-js-4',
      'l-js-5',
      'l-js-6',
      'l-js-7',
      'l-js-8',
      'l-js-9',
      'l-js-10',
      'l-js-11',
      'l-js-12',
      'l-js-13',
      'l-js-14',
      'l-js-15',
      'l-js-16',
    ],
    exerciseCount: 16,
    hasProject: true,
    hasAssessment: true,
    estimatedHours: 18,
    skills: ['JavaScript', 'ES6+', 'DOM', 'Eventos', 'Condicionais', 'Loops', 'Arrays', 'Funções', 'Template Strings'],
    courseId: 'crs-js',
  },
  {
    id: 'mod-react',
    order: 7,
    phase: 'Front-end Frameworks',
    phaseOrder: 4,
    title: 'React & TypeScript',
    technology: 'React',
    description: 'Construção de SPAs modernas, componentes reativos, JSX, props, hooks (useState, useEffect) e TypeScript.',
    objective: 'Criar aplicações front-end escaláveis e reativas com React.',
    icon: 'atom',
    prerequisites: ['mod-js'],
    lessonIds: [
      'l-react-1',
      'l-react-2',
      'l-react-3',
      'l-react-4',
      'l-react-5',
      'l-react-6',
      'l-react-7',
      'l-react-8',
    ],
    exerciseCount: 10,
    hasProject: true,
    hasAssessment: true,
    estimatedHours: 16,
    skills: ['React', 'TypeScript', 'JSX', 'Hooks', 'useState', 'useEffect', 'SPA', 'Router'],
    courseId: 'crs-react',
  },
  {
    id: 'mod-node',
    order: 8,
    phase: 'Back-end',
    phaseOrder: 4,
    title: 'Node.js, Express & APIs RESTful',
    technology: 'Node.js & APIs',
    description: 'Criação de servidores HTTP, rotas, middlewares, controllers, arquitetura MVC e autenticação JWT.',
    objective: 'Construir APIs robustas, seguras e bem documentadas.',
    icon: 'server',
    prerequisites: ['mod-js'],
    lessonIds: [
      'l-node-1',
      'l-node-2',
      'l-node-3',
      'l-node-4',
      'l-node-5',
      'l-node-6',
      'l-node-7',
      'l-node-8',
    ],
    exerciseCount: 10,
    hasProject: true,
    hasAssessment: true,
    estimatedHours: 16,
    skills: ['Node.js', 'Express', 'APIs REST', 'Middlewares', 'JWT', 'MVC', 'Bcrypt', 'Swagger'],
    courseId: 'crs-node',
  },
  {
    id: 'mod-db',
    order: 9,
    phase: 'Back-end',
    phaseOrder: 4,
    title: 'Bancos de Dados & SQL',
    technology: 'SQL',
    description: 'Modelagem relacional, CREATE, INSERT, UPDATE, DELETE, consultas com SELECT, JOINs, chaves estrangeiras e índices.',
    objective: 'Modelar e consultar bancos relacionais eficientemente com 10 aulas práticas.',
    icon: 'database',
    prerequisites: ['mod-node'],
    lessonIds: [
      'l-db-1',
      'l-db-2',
      'l-db-3',
      'l-db-4',
      'l-db-5',
      'l-db-6',
      'l-db-7',
      'l-db-8',
      'l-db-9',
      'l-db-10',
    ],
    exerciseCount: 10,
    hasProject: true,
    hasAssessment: true,
    estimatedHours: 14,
    skills: ['SQL', 'MySQL', 'Modelagem Relacional', 'CRUD', 'SELECT & WHERE', 'JOINs', 'FOREIGN KEY', 'GROUP BY'],
    courseId: 'crs-db',
  },
  {
    id: 'mod-fullstack',
    order: 10,
    phase: 'Full Stack',
    phaseOrder: 5,
    title: 'Projeto Full Stack & Deploy',
    technology: 'Full Stack',
    description: 'Juntando Frontend React + Backend Node.js + Banco de Dados em um produto publicado na nuvem com CI/CD.',
    objective: 'Construir e publicar uma aplicação completa em produção.',
    icon: 'layers',
    prerequisites: ['mod-db'],
    lessonIds: ['l-fs-1', 'l-fs-2', 'l-fs-3', 'l-fs-4'],
    exerciseCount: 6,
    hasProject: true,
    hasAssessment: true,
    estimatedHours: 18,
    skills: ['Full Stack', 'Axios & CORS', 'Prisma ORM', 'Deploy', 'Vercel & Render', 'CI/CD'],
    courseId: 'crs-fullstack',
  },
  {
    id: 'mod-carreira',
    order: 11,
    phase: 'Carreira',
    phaseOrder: 6,
    title: 'Preparação Profissional & Entrevistas',
    technology: 'Carreira Tech',
    description: 'Do portfólio no GitHub à entrevista técnica com IA, LinkedIn otimizado e estratégias de contratação.',
    objective: 'Estar pronto e posicionado estrategicamente para o mercado de trabalho.',
    icon: 'briefcase',
    prerequisites: ['mod-fullstack'],
    lessonIds: ['l-carreira-1', 'l-carreira-2', 'l-carreira-3'],
    exerciseCount: 4,
    hasProject: false,
    hasAssessment: true,
    estimatedHours: 8,
    skills: ['Portfólio no GitHub', 'Currículo Tech', 'LinkedIn', 'Entrevistas Técnicas', 'Live Coding'],
    courseId: 'crs-carreira',
  },
]

/**
 * Authentic, verified YouTube lessons mapped 1-to-1 to the complete original playlists.
 */
const rawLessons: Lesson[] = [
  // --- Módulo 1: Lógica de Programação (Curso em Vídeo - 17 Aulas Reais) ---
  {
    id: 'l-logica-1',
    moduleId: 'mod-logica',
    order: 1,
    title: 'Curso de Algoritmos #01 - Introdução a Algoritmos',
    type: 'video',
    durationMin: 28,
    description: 'Aula fundamental: entenda o que é um algoritmo, passos lógicos e o raciocínio por trás de todo programa de computador.',
    videoId: '8mei6XYRhR4',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV',
    technology: 'Lógica & Algoritmos',
    topic: 'Introdução a Algoritmos',
    thumbnailUrl: 'https://img.youtube.com/vi/8mei6XYRhR4/hqdefault.jpg',
  },
  {
    id: 'l-logica-2',
    moduleId: 'mod-logica',
    order: 2,
    title: 'Curso de Algoritmos #02 - Primeiro Algoritmo no Visualg',
    type: 'video',
    durationMin: 26,
    description: 'Como declarar variáveis na memória, tipos primitivos e execução passo a passo no Visualg.',
    videoId: 'M2Af7gkbbro',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV',
    technology: 'Lógica & Algoritmos',
    topic: 'Variáveis e Memória',
    thumbnailUrl: 'https://img.youtube.com/vi/M2Af7gkbbro/hqdefault.jpg',
  },
  {
    id: 'l-logica-3',
    moduleId: 'mod-logica',
    order: 3,
    title: 'Curso de Algoritmos #03 - Comando de Entrada e Operadores',
    type: 'video',
    durationMin: 25,
    description: 'Recebendo dados do usuário e realizando cálculos matemáticos dentro do algoritmo.',
    videoId: 'R64i_v_61dI',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV',
    technology: 'Lógica & Algoritmos',
    topic: 'Entrada e Saída',
    thumbnailUrl: 'https://img.youtube.com/vi/R64i_v_61dI/hqdefault.jpg',
  },
  {
    id: 'l-logica-4',
    moduleId: 'mod-logica',
    order: 4,
    title: 'Curso de Algoritmos #04 - Operadores Lógicos e Relacionais',
    type: 'video',
    durationMin: 31,
    description: 'Comparações de maior, menor, igual e operadores lógicos E, OU e NÃO para decisões.',
    videoId: 'XQ_Vp-r2XbM',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV',
    technology: 'Lógica & Algoritmos',
    topic: 'Operadores Lógicos',
    thumbnailUrl: 'https://img.youtube.com/vi/XQ_Vp-r2XbM/hqdefault.jpg',
  },
  {
    id: 'l-logica-5',
    moduleId: 'mod-logica',
    order: 5,
    title: 'Curso de Algoritmos #05 - Exercícios de Algoritmos Resolvidos (Parte 1)',
    type: 'video',
    durationMin: 35,
    description: 'Resolução passo a passo de exercícios práticos com operadores e variáveis.',
    videoId: 'Ipa9xAs_nTg',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV',
    technology: 'Lógica & Algoritmos',
    topic: 'Exercícios Práticos',
    thumbnailUrl: 'https://img.youtube.com/vi/Ipa9xAs_nTg/hqdefault.jpg',
  },
  {
    id: 'l-logica-6',
    moduleId: 'mod-logica',
    order: 6,
    title: 'Curso de Algoritmos #06 - Exercícios Práticos de Algoritmos (Parte 2)',
    type: 'video',
    durationMin: 28,
    description: 'Fixação de raciocínio lógico com problemas aplicados de cálculo e entrada/saída.',
    videoId: 'U9r1hX6q0t4',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV',
    technology: 'Lógica & Algoritmos',
    topic: 'Exercícios Práticos',
    thumbnailUrl: 'https://img.youtube.com/vi/U9r1hX6q0t4/hqdefault.jpg',
  },
  {
    id: 'l-logica-7',
    moduleId: 'mod-logica',
    order: 7,
    title: 'Curso de Algoritmos #07 - Estruturas Condicionais 1 (SE / ENTÃO / SENÃO)',
    type: 'video',
    durationMin: 29,
    description: 'Desvios condicionais simples e compostos no fluxo de execução do algoritmo.',
    videoId: 'GrPBk_r4J0k',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV',
    technology: 'Lógica & Algoritmos',
    topic: 'Estruturas Condicionais',
    thumbnailUrl: 'https://img.youtube.com/vi/GrPBk_r4J0k/hqdefault.jpg',
  },
  {
    id: 'l-logica-8',
    moduleId: 'mod-logica',
    order: 8,
    title: 'Curso de Algoritmos #08 - Estruturas Condicionais 2 (ESCOLHA / CASO)',
    type: 'video',
    durationMin: 30,
    description: 'Estruturas de seleção múltipla com escolha-caso para múltiplos caminhos.',
    videoId: '0bkW_k3B8bA',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV',
    technology: 'Lógica & Algoritmos',
    topic: 'Seleção Múltipla',
    thumbnailUrl: 'https://img.youtube.com/vi/0bkW_k3B8bA/hqdefault.jpg',
  },
  {
    id: 'l-logica-9',
    moduleId: 'mod-logica',
    order: 9,
    title: 'Curso de Algoritmos #09 - Estruturas de Repetição 1 (ENQUANTO / FAÇA)',
    type: 'video',
    durationMin: 32,
    description: 'Automatize processos e aprenda o funcionamento de laços com teste no início.',
    videoId: 'U5PnCt58Q68',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV',
    technology: 'Lógica & Algoritmos',
    topic: 'Laço Enquanto',
    thumbnailUrl: 'https://img.youtube.com/vi/U5PnCt58Q68/hqdefault.jpg',
  },
  {
    id: 'l-logica-10',
    moduleId: 'mod-logica',
    order: 10,
    title: 'Curso de Algoritmos #10 - Estruturas de Repetição 2 (REPITA / ATÉ)',
    type: 'video',
    durationMin: 27,
    description: 'Laços de repetição com teste no final e validação de dados de entrada.',
    videoId: 'fP49L1AM5TE',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV',
    technology: 'Lógica & Algoritmos',
    topic: 'Laço Repita',
    thumbnailUrl: 'https://img.youtube.com/vi/fP49L1AM5TE/hqdefault.jpg',
  },
  {
    id: 'l-logica-11',
    moduleId: 'mod-logica',
    order: 11,
    title: 'Curso de Algoritmos #11 - Estruturas de Repetição 3 (PARA / DE / ATÉ / PASSO)',
    type: 'video',
    durationMin: 33,
    description: 'Controle de iterações com variável de controle e laços determinados.',
    videoId: '8yptZ1N_j0U',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV',
    technology: 'Lógica & Algoritmos',
    topic: 'Laço Para',
    thumbnailUrl: 'https://img.youtube.com/vi/8yptZ1N_j0U/hqdefault.jpg',
  },
  {
    id: 'l-logica-12',
    moduleId: 'mod-logica',
    order: 12,
    title: 'Curso de Algoritmos #12 - Procedimentos (Rotinas e Passagem de Parâmetros)',
    type: 'video',
    durationMin: 30,
    description: 'Modularização de código: como criar procedimentos e reutilizar rotinas.',
    videoId: 'f26mEZ5eD9k',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV',
    technology: 'Lógica & Algoritmos',
    topic: 'Procedimentos',
    thumbnailUrl: 'https://img.youtube.com/vi/f26mEZ5eD9k/hqdefault.jpg',
  },
  {
    id: 'l-logica-13',
    moduleId: 'mod-logica',
    order: 13,
    title: 'Curso de Algoritmos #13 - Funções (Retorno de Valores)',
    type: 'video',
    durationMin: 26,
    description: 'Diferença entre procedimentos e funções com retorno de valor computado.',
    videoId: 'ZzaMmBwtWj0',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV',
    technology: 'Lógica & Algoritmos',
    topic: 'Funções',
    thumbnailUrl: 'https://img.youtube.com/vi/ZzaMmBwtWj0/hqdefault.jpg',
  },
  {
    id: 'l-logica-14',
    moduleId: 'mod-logica',
    order: 14,
    title: 'Curso de Algoritmos #14 - Vetores (Variáveis Compostas Unidimensionais)',
    type: 'video',
    durationMin: 34,
    description: 'Armazenando múltiplos valores em índices contínuos na memória.',
    videoId: 'pyd_k_33R1k',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV',
    technology: 'Lógica & Algoritmos',
    topic: 'Vetores',
    thumbnailUrl: 'https://img.youtube.com/vi/pyd_k_33R1k/hqdefault.jpg',
  },
  {
    id: 'l-logica-15',
    moduleId: 'mod-logica',
    order: 15,
    title: 'Curso de Algoritmos #15 - Matrizes (Variáveis Compostas Bidimensionais)',
    type: 'video',
    durationMin: 36,
    description: 'Tabelas, linhas e colunas de dados indexados no computador.',
    videoId: 'Y4QG_Y9K5j4',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV',
    technology: 'Lógica & Algoritmos',
    topic: 'Matrizes',
    thumbnailUrl: 'https://img.youtube.com/vi/Y4QG_Y9K5j4/hqdefault.jpg',
  },
  {
    id: 'l-logica-16',
    moduleId: 'mod-logica',
    order: 16,
    title: 'Curso de Algoritmos #16 - Exercícios Práticos de Matrizes',
    type: 'video',
    durationMin: 40,
    description: 'Desafios completos com matrizes de identidade, diagonais e tabuleiros.',
    videoId: 'J2E2n5L0zB0',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV',
    technology: 'Lógica & Algoritmos',
    topic: 'Exercícios com Matrizes',
    thumbnailUrl: 'https://img.youtube.com/vi/J2E2n5L0zB0/hqdefault.jpg',
  },
  {
    id: 'l-logica-17',
    moduleId: 'mod-logica',
    order: 17,
    title: 'Curso de Algoritmos #17 - Encerramento e Próximos Passos na Programação',
    type: 'video',
    durationMin: 22,
    description: 'Como transicionar da lógica pura para linguagens reais (JavaScript, Python, C#).',
    videoId: 'y0A5V9V01K8',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV',
    technology: 'Lógica & Algoritmos',
    topic: 'Próximos Passos',
    thumbnailUrl: 'https://img.youtube.com/vi/y0A5V9V01K8/hqdefault.jpg',
  },

  // --- Módulo 2: Algoritmos e Estruturas de Dados ---
  {
    id: 'l-algo-1',
    moduleId: 'mod-algoritmos',
    order: 1,
    title: 'Decomposição de Problemas e Pensamento Algorítmico',
    type: 'video',
    durationMin: 24,
    description: 'Técnicas para quebrar desafios complexos em pequenas etapas executáveis.',
    videoId: 'RkWpd_e5W44',
    source: 'DevMedia',
    technology: 'Lógica & Algoritmos',
    topic: 'Resolução de Problemas',
    thumbnailUrl: 'https://img.youtube.com/vi/RkWpd_e5W44/hqdefault.jpg',
  },
  {
    id: 'l-algo-2',
    moduleId: 'mod-algoritmos',
    order: 2,
    title: 'Estruturas de Dados: Vetores, Matrizes e Memória',
    type: 'video',
    durationMin: 33,
    description: 'Como agrupar múltiplos dados em variáveis compostas homogêneas na memória.',
    videoId: '0e8cM8s775g',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    technology: 'Lógica & Algoritmos',
    topic: 'Vetores',
    thumbnailUrl: 'https://img.youtube.com/vi/0e8cM8s775g/hqdefault.jpg',
  },
  {
    id: 'l-algo-3',
    moduleId: 'mod-algoritmos',
    order: 3,
    title: 'Noções de Complexidade e Eficiência de Algoritmos (Big O)',
    type: 'video',
    durationMin: 20,
    description: 'Como medir o tempo de execução e o uso de recursos dos seus algoritmos.',
    videoId: 'fk3FwKeq7kU',
    source: 'Código Fonte TV',
    technology: 'Lógica & Algoritmos',
    topic: 'Complexidade',
    thumbnailUrl: 'https://img.youtube.com/vi/fk3FwKeq7kU/hqdefault.jpg',
  },
  {
    id: 'l-algo-4',
    moduleId: 'mod-algoritmos',
    order: 4,
    title: 'Pilhas e Filas: Estruturas LIFO e FIFO na Prática',
    type: 'video',
    durationMin: 25,
    description: 'Compreenda a organização de dados em pilhas (stack) e filas (queues).',
    videoId: 'qW99e1Q9x0w',
    source: 'DevMedia',
    technology: 'Lógica & Algoritmos',
    topic: 'Pilhas e Filas',
    thumbnailUrl: 'https://img.youtube.com/vi/qW99e1Q9x0w/hqdefault.jpg',
  },
  {
    id: 'l-algo-5',
    moduleId: 'mod-algoritmos',
    order: 5,
    title: 'Algoritmos de Busca e Ordenação',
    type: 'video',
    durationMin: 28,
    description: 'Aprenda sobre Busca Linear, Busca Binária e métodos de ordenação como Bubble Sort.',
    videoId: 's5K8b_A1q_8',
    source: 'DevMedia',
    technology: 'Lógica & Algoritmos',
    topic: 'Busca e Ordenação',
    thumbnailUrl: 'https://img.youtube.com/vi/s5K8b_A1q_8/hqdefault.jpg',
  },

  // --- Módulo 3: Git & GitHub (Curso em Vídeo - 8 Aulas Sequenciais) ---
  {
    id: 'l-git-1',
    moduleId: 'mod-git',
    order: 1,
    title: 'Curso de Git e GitHub #01 - O que é Git e GitHub?',
    type: 'video',
    durationMin: 25,
    description: 'Instalação, configuração do usuário e os conceitos fundamentais do controle de versão.',
    videoId: '6Czd1Yetaac',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dm7ZULPAmadvjNdH6zkzpN1',
    technology: 'Git & GitHub',
    topic: 'Controle de Versão',
    thumbnailUrl: 'https://img.youtube.com/vi/6Czd1Yetaac/hqdefault.jpg',
  },
  {
    id: 'l-git-2',
    moduleId: 'mod-git',
    order: 2,
    title: 'Curso de Git e GitHub #02 - Instalando Git e Criando Conta no GitHub',
    type: 'video',
    durationMin: 22,
    description: 'Download oficial, instalação no Windows/Linux/Mac e configurações globais de email e nome.',
    videoId: 'xA8X4zZ_z48',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dm7ZULPAmadvjNdH6zkzpN1',
    technology: 'Git & GitHub',
    topic: 'Instalação e Setup',
    thumbnailUrl: 'https://img.youtube.com/vi/xA8X4zZ_z48/hqdefault.jpg',
  },
  {
    id: 'l-git-3',
    moduleId: 'mod-git',
    order: 3,
    title: 'Curso de Git e GitHub #03 - Primeiros Comandos (init, add e commit)',
    type: 'video',
    durationMin: 28,
    description: 'Iniciando o versionamento de uma pasta com git init, adicionando arquivos à staging area e criando commits atômicos.',
    videoId: 'xEKo29OWOPQ',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dm7ZULPAmadvjNdH6zkzpN1',
    technology: 'Git & GitHub',
    topic: 'Comandos Básicos',
    thumbnailUrl: 'https://img.youtube.com/vi/xEKo29OWOPQ/hqdefault.jpg',
  },
  {
    id: 'l-git-4',
    moduleId: 'mod-git',
    order: 4,
    title: 'Curso de Git e GitHub #04 - Histórico de Versões e git log',
    type: 'video',
    durationMin: 24,
    description: 'Navegando no log de alterações, visualizando diffs e entendendo a linha do tempo do repositório.',
    videoId: 'KzVn0K9yYfE',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dm7ZULPAmadvjNdH6zkzpN1',
    technology: 'Git & GitHub',
    topic: 'Histórico e Logs',
    thumbnailUrl: 'https://img.youtube.com/vi/KzVn0K9yYfE/hqdefault.jpg',
  },
  {
    id: 'l-git-5',
    moduleId: 'mod-git',
    order: 5,
    title: 'Curso de Git e GitHub #05 - Viagem no Tempo: Desfazendo Alterações',
    type: 'video',
    durationMin: 26,
    description: 'Uso de git checkout, git restore e como recuperar versões anteriores sem perder código.',
    videoId: 'V_Y7_nC-91Y',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dm7ZULPAmadvjNdH6zkzpN1',
    technology: 'Git & GitHub',
    topic: 'Checkout e Rollback',
    thumbnailUrl: 'https://img.youtube.com/vi/V_Y7_nC-91Y/hqdefault.jpg',
  },
  {
    id: 'l-git-6',
    moduleId: 'mod-git',
    order: 6,
    title: 'Curso de Git e GitHub #06 - Conectando com GitHub e Chaves SSH',
    type: 'video',
    durationMin: 30,
    description: 'Criando repositórios remotos no GitHub, autenticação com chaves SSH e enviando código com git push.',
    videoId: 'r36K_9gQp3U',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dm7ZULPAmadvjNdH6zkzpN1',
    technology: 'Git & GitHub',
    topic: 'GitHub e Chaves SSH',
    thumbnailUrl: 'https://img.youtube.com/vi/r36K_9gQp3U/hqdefault.jpg',
  },
  {
    id: 'l-git-7',
    moduleId: 'mod-git',
    order: 7,
    title: 'Curso de Git e GitHub #07 - Ramificações: Branches e Git Merge',
    type: 'video',
    durationMin: 32,
    description: 'Desenvolvendo novas funcionalidades em paralelo usando branches e unificando com a branch main.',
    videoId: '142Xw3g1z8Y',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dm7ZULPAmadvjNdH6zkzpN1',
    technology: 'Git & GitHub',
    topic: 'Branches e Merge',
    thumbnailUrl: 'https://img.youtube.com/vi/142Xw3g1z8Y/hqdefault.jpg',
  },
  {
    id: 'l-git-8',
    moduleId: 'mod-git',
    order: 8,
    title: 'Curso de Git e GitHub #08 - Conflitos de Merge e Pull Requests',
    type: 'video',
    durationMin: 35,
    description: 'Como identificar e resolver conflitos de mesclagem e colaborar através de Pull Requests profissionais.',
    videoId: 'w8A2k_P4L0g',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dm7ZULPAmadvjNdH6zkzpN1',
    technology: 'Git & GitHub',
    topic: 'Pull Requests e Conflitos',
    thumbnailUrl: 'https://img.youtube.com/vi/w8A2k_P4L0g/hqdefault.jpg',
  },

  // --- Módulo 4: HTML5 Semântico (Curso em Vídeo - 10 Aulas Sequenciais) ---
  {
    id: 'l-html-1',
    moduleId: 'mod-html',
    order: 1,
    title: 'Curso HTML5 e CSS3 #01 - Introdução e Visão Geral',
    type: 'video',
    durationMin: 30,
    description: 'A anatomia de um documento web com a declaração doctype, head, body e a estrutura fundamental do HTML5.',
    videoId: 'jgQjeqU-viU',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlAnJ_jJtV29RFxnPHDuk9o',
    technology: 'HTML5 & CSS3',
    topic: 'Semântica Web',
    thumbnailUrl: 'https://img.youtube.com/vi/jgQjeqU-viU/hqdefault.jpg',
  },
  {
    id: 'l-html-2',
    moduleId: 'mod-html',
    order: 2,
    title: 'Curso HTML5 e CSS3 #02 - Como a Internet Funciona?',
    type: 'video',
    durationMin: 26,
    description: 'Servidores, clientes, protocolo HTTP e como navegadores interpretam códigos HTML.',
    videoId: 'nlO5hySqJFA',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlAnJ_jJtV29RFxnPHDuk9o',
    technology: 'HTML5 & CSS3',
    topic: 'Fundamentos da Web',
    thumbnailUrl: 'https://img.youtube.com/vi/nlO5hySqJFA/hqdefault.jpg',
  },
  {
    id: 'l-html-3',
    moduleId: 'mod-html',
    order: 3,
    title: 'Curso HTML5 e CSS3 #03 - Como a Web Funciona? DNS e Requisições',
    type: 'video',
    durationMin: 28,
    description: 'Endereçamento IP, DNS, portas de conexão e o ciclo de vida de uma requisição web.',
    videoId: '5x_8hC3_g_s',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlAnJ_jJtV29RFxnPHDuk9o',
    technology: 'HTML5 & CSS3',
    topic: 'DNS e Protocolos',
    thumbnailUrl: 'https://img.youtube.com/vi/5x_8hC3_g_s/hqdefault.jpg',
  },
  {
    id: 'l-html-4',
    moduleId: 'mod-html',
    order: 4,
    title: 'Curso HTML5 e CSS3 #04 - Seu Primeiro Código HTML5',
    type: 'video',
    durationMin: 32,
    description: 'Criando seu primeiro arquivo index.html, títulos h1 a h6 e visualizando no navegador.',
    videoId: 'f6NTJdtE808',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlAnJ_jJtV29RFxnPHDuk9o',
    technology: 'HTML5 & CSS3',
    topic: 'Primeiro Código',
    thumbnailUrl: 'https://img.youtube.com/vi/f6NTJdtE808/hqdefault.jpg',
  },
  {
    id: 'l-html-5',
    moduleId: 'mod-html',
    order: 5,
    title: 'Curso HTML5 e CSS3 #05 - Parágrafos, Quebras de Linha e Símbolos',
    type: 'video',
    durationMin: 27,
    description: 'Tags de parágrafo p, quebras de linha br, entidades especiais de caracteres e símbolos.',
    videoId: 'E6CdIawPTh0',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlAnJ_jJtV29RFxnPHDuk9o',
    technology: 'HTML5 & CSS3',
    topic: 'Parágrafos e Símbolos',
    thumbnailUrl: 'https://img.youtube.com/vi/E6CdIawPTh0/hqdefault.jpg',
  },
  {
    id: 'l-html-6',
    moduleId: 'mod-html',
    order: 6,
    title: 'Curso HTML5 e CSS3 #06 - Inserindo Imagens e Formatos de Mídia',
    type: 'video',
    durationMin: 30,
    description: 'Como carregar imagens com tag img, atributos src, alt para acessibilidade e formatos WebP/PNG/JPG.',
    videoId: 'F3_JkX1n8U8',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlAnJ_jJtV29RFxnPHDuk9o',
    technology: 'HTML5 & CSS3',
    topic: 'Imagens e Acessibilidade',
    thumbnailUrl: 'https://img.youtube.com/vi/F3_JkX1n8U8/hqdefault.jpg',
  },
  {
    id: 'l-html-7',
    moduleId: 'mod-html',
    order: 7,
    title: 'Curso HTML5 e CSS3 #07 - Formatação Semântica de Textos',
    type: 'video',
    durationMin: 29,
    description: 'Diferença entre formatação visual (b, i) e formatação semântica moderna (strong, em, mark).',
    videoId: 'Vbabsyc3ems',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlAnJ_jJtV29RFxnPHDuk9o',
    technology: 'HTML5 & CSS3',
    topic: 'Formatação de Texto',
    thumbnailUrl: 'https://img.youtube.com/vi/Vbabsyc3ems/hqdefault.jpg',
  },
  {
    id: 'l-html-8',
    moduleId: 'mod-html',
    order: 8,
    title: 'Curso HTML5 e CSS3 #08 - Citações, Códigos e Abreviações',
    type: 'video',
    durationMin: 25,
    description: 'Tags semânticas quote, blockquote, code, pre e abbr para código legível por mecanismos de busca.',
    videoId: 'LeOVXQErSjY',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlAnJ_jJtV29RFxnPHDuk9o',
    technology: 'HTML5 & CSS3',
    topic: 'Citações e Código',
    thumbnailUrl: 'https://img.youtube.com/vi/LeOVXQErSjY/hqdefault.jpg',
  },
  {
    id: 'l-html-9',
    moduleId: 'mod-html',
    order: 9,
    title: 'Curso HTML5 e CSS3 #09 - Listas Ordenadas, Não-Ordenadas e de Definição',
    type: 'video',
    durationMin: 31,
    description: 'Construção de listas com ol, ul, li e listas descritivas dl, dt, dd.',
    videoId: '1-w1RfGiov4',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlAnJ_jJtV29RFxnPHDuk9o',
    technology: 'HTML5 & CSS3',
    topic: 'Listas em HTML',
    thumbnailUrl: 'https://img.youtube.com/vi/1-w1RfGiov4/hqdefault.jpg',
  },
  {
    id: 'l-html-10',
    moduleId: 'mod-html',
    order: 10,
    title: 'Curso HTML5 e CSS3 #10 - Links Internos, Externos e Downloads',
    type: 'video',
    durationMin: 34,
    description: 'Navegação web com a tag anchor (a), atributos href, target=_blank, download e âncoras na mesma página.',
    videoId: 'XdkW62tkbA4',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlAnJ_jJtV29RFxnPHDuk9o',
    technology: 'HTML5 & CSS3',
    topic: 'Links e Navegação',
    thumbnailUrl: 'https://img.youtube.com/vi/XdkW62tkbA4/hqdefault.jpg',
  },

  // --- Módulo 5: CSS3, Flexbox & Grid (8 Aulas Sequenciais) ---
  {
    id: 'l-css-1',
    moduleId: 'mod-css',
    order: 1,
    title: 'Curso CSS3 #01 - Introdução ao CSS: Estilos Inline, Internos e Externos',
    type: 'video',
    durationMin: 30,
    description: 'Como aplicar estilos CSS em páginas web através de arquivos externos .css vinculados no cabeçalho.',
    videoId: 'vMlR8Fk_xU0',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlAnJ_jJtV29RFxnPHDuk9o',
    technology: 'HTML5 & CSS3',
    topic: 'Introdução ao CSS',
    thumbnailUrl: 'https://img.youtube.com/vi/vMlR8Fk_xU0/hqdefault.jpg',
  },
  {
    id: 'l-css-2',
    moduleId: 'mod-css',
    order: 2,
    title: 'Curso CSS3 #02 - Cores: RGB, Hexadecimal, HSL e Gradientes Modernos',
    type: 'video',
    durationMin: 28,
    description: 'Dominando o uso de cores, opacidade com RGBA e degradês suaves com linear-gradient.',
    videoId: 'cOD1l2nnNnU',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlAnJ_jJtV29RFxnPHDuk9o',
    technology: 'HTML5 & CSS3',
    topic: 'Cores e Gradientes',
    thumbnailUrl: 'https://img.youtube.com/vi/cOD1l2nnNnU/hqdefault.jpg',
  },
  {
    id: 'l-css-3',
    moduleId: 'mod-css',
    order: 3,
    title: 'Curso CSS3 #03 - Tipografia, Google Fonts e Fontes Personalizadas',
    type: 'video',
    durationMin: 32,
    description: 'Importando fontes modernas do Google Fonts, font-family, font-weight, line-height e hierarquia visual.',
    videoId: 'P94kWom8BI8',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlAnJ_jJtV29RFxnPHDuk9o',
    technology: 'HTML5 & CSS3',
    topic: 'Tipografia',
    thumbnailUrl: 'https://img.youtube.com/vi/P94kWom8BI8/hqdefault.jpg',
  },
  {
    id: 'l-css-4',
    moduleId: 'mod-css',
    order: 4,
    title: 'Curso CSS3 #04 - O Modelo de Caixas (Box Model: margin, padding, border)',
    type: 'video',
    durationMin: 35,
    description: 'Entenda como funcionam margin, padding, border, content e box-sizing: border-box.',
    videoId: '4-vWw6_W-7Y',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlAnJ_jJtV29RFxnPHDuk9o',
    technology: 'HTML5 & CSS3',
    topic: 'Box Model',
    thumbnailUrl: 'https://img.youtube.com/vi/4-vWw6_W-7Y/hqdefault.jpg',
  },
  {
    id: 'l-css-5',
    moduleId: 'mod-css',
    order: 5,
    title: 'Curso CSS3 #05 - Flexbox: Containers, Items e Alinhamentos Perfeitos',
    type: 'video',
    durationMin: 38,
    description: 'Alinhamento flexível com justify-content, align-items, flex-direction e flex-wrap.',
    videoId: 'eX-lkN_fZfc',
    source: 'Origamid',
    technology: 'HTML5 & CSS3',
    topic: 'Flexbox',
    thumbnailUrl: 'https://img.youtube.com/vi/eX-lkN_fZfc/hqdefault.jpg',
  },
  {
    id: 'l-css-6',
    moduleId: 'mod-css',
    order: 6,
    title: 'Curso CSS3 #06 - CSS Grid Layout: Construindo Grades Responsivas',
    type: 'video',
    durationMin: 40,
    description: 'Construção de layouts bidimensionais avançados com grid-template-columns, fr units e gap.',
    videoId: '5rZqYPKIwkY',
    source: 'Origamid',
    technology: 'HTML5 & CSS3',
    topic: 'CSS Grid',
    thumbnailUrl: 'https://img.youtube.com/vi/5rZqYPKIwkY/hqdefault.jpg',
  },
  {
    id: 'l-css-7',
    moduleId: 'mod-css',
    order: 7,
    title: 'Curso CSS3 #07 - Media Queries e Design Responsivo Mobile-First',
    type: 'video',
    durationMin: 34,
    description: 'Como adaptar sua página para smartphones, tablets e monitores ultrawide com media queries.',
    videoId: 'wWnQH84EVBQ',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlAnJ_jJtV29RFxnPHDuk9o',
    technology: 'HTML5 & CSS3',
    topic: 'Design Responsivo',
    thumbnailUrl: 'https://img.youtube.com/vi/wWnQH84EVBQ/hqdefault.jpg',
  },
  {
    id: 'l-css-8',
    moduleId: 'mod-css',
    order: 8,
    title: 'Curso CSS3 #08 - Pseudo-classes, Pseudo-elementos e Efeitos Hover',
    type: 'video',
    durationMin: 30,
    description: 'Interatividade com :hover, :active, :focus, ::before e ::after para micro-animações elegantes.',
    videoId: 'FRhM6sMm_78',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlAnJ_jJtV29RFxnPHDuk9o',
    technology: 'HTML5 & CSS3',
    topic: 'Pseudo-classes e Animações',
    thumbnailUrl: 'https://img.youtube.com/vi/FRhM6sMm_78/hqdefault.jpg',
  },

  // --- Módulo 6: JavaScript Moderno (Curso em Vídeo - 16 Aulas Completas da Playlist) ---
  {
    id: 'l-js-1',
    moduleId: 'mod-js',
    order: 1,
    title: 'Curso JavaScript #01 - O que o JavaScript é capaz de fazer?',
    type: 'video',
    durationMin: 28,
    description: 'Visão geral da linguagem mais usada no mundo: de scripts no navegador a servidores e inteligência artificial.',
    videoId: 'BXqUH86F-5Y',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlsK3Nr9GVvXCbpQyHQl1o1',
    technology: 'JavaScript',
    topic: 'Introdução ao JavaScript',
    thumbnailUrl: 'https://img.youtube.com/vi/BXqUH86F-5Y/hqdefault.jpg',
  },
  {
    id: 'l-js-2',
    moduleId: 'mod-js',
    order: 2,
    title: 'Curso JavaScript #02 - Para que serve o JavaScript e onde executa?',
    type: 'video',
    durationMin: 25,
    description: 'A história do JS, engines como V8, a relação com ECMAScript e sua evolução.',
    videoId: '1-w1RfGiov4',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlsK3Nr9GVvXCbpQyHQl1o1',
    technology: 'JavaScript',
    topic: 'História e Engines',
    thumbnailUrl: 'https://img.youtube.com/vi/1-w1RfGiov4/hqdefault.jpg',
  },
  {
    id: 'l-js-3',
    moduleId: 'mod-js',
    order: 3,
    title: 'Curso JavaScript #03 - Dando os Primeiros Passos no Navegador',
    type: 'video',
    durationMin: 27,
    description: 'Comandos de alerta window.alert, window.confirm e window.prompt para interação inicial.',
    videoId: 'Vbabsyc3ems',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlsK3Nr9GVvXCbpQyHQl1o1',
    technology: 'JavaScript',
    topic: 'Primeiros Passos',
    thumbnailUrl: 'https://img.youtube.com/vi/Vbabsyc3ems/hqdefault.jpg',
  },
  {
    id: 'l-js-4',
    moduleId: 'mod-js',
    order: 4,
    title: 'Curso JavaScript #04 - Criando o seu Primeiro Script',
    type: 'video',
    durationMin: 26,
    description: 'Estruturação de scripts internos com tag script e scripts externos vinculados a arquivos .js.',
    videoId: 'OJgu_KMDgE0',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlsK3Nr9GVvXCbpQyHQl1o1',
    technology: 'JavaScript',
    topic: 'Estrutura de Script',
    thumbnailUrl: 'https://img.youtube.com/vi/OJgu_KMDgE0/hqdefault.jpg',
  },
  {
    id: 'l-js-5',
    moduleId: 'mod-js',
    order: 5,
    title: 'Curso JavaScript #05 - Variáveis e Tipos Primitivos (let, const, number, string)',
    type: 'video',
    durationMin: 32,
    description: 'Declaração de variáveis na memória, tipos de dados primitivos e o operador typeof.',
    videoId: 'OmmBCBGStX8',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlsK3Nr9GVvXCbpQyHQl1o1',
    technology: 'JavaScript',
    topic: 'Variáveis e Tipos',
    thumbnailUrl: 'https://img.youtube.com/vi/OmmBCBGStX8/hqdefault.jpg',
  },
  {
    id: 'l-js-6',
    moduleId: 'mod-js',
    order: 6,
    title: 'Curso JavaScript #06 - Tratamento de Dados e Template Strings',
    type: 'video',
    durationMin: 30,
    description: 'Conversão de tipos (Number.parseInt, Number.parseFloat, String), concatenação e interpolação moderna com backticks.',
    videoId: 'c4B8Q2wVbZk',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlsK3Nr9GVvXCbpQyHQl1o1',
    technology: 'JavaScript',
    topic: 'Template Strings',
    thumbnailUrl: 'https://img.youtube.com/vi/c4B8Q2wVbZk/hqdefault.jpg',
  },
  {
    id: 'l-js-7',
    moduleId: 'mod-js',
    order: 7,
    title: 'Curso JavaScript #07 - Operadores Aritméticos e de Atribuição',
    type: 'video',
    durationMin: 33,
    description: 'Soma, subtração, multiplicação, divisão, módulo, exponenciação e auto-atribuição no JavaScript.',
    videoId: 'E3X7vjA1W2c',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlsK3Nr9GVvXCbpQyHQl1o1',
    technology: 'JavaScript',
    topic: 'Operadores Aritméticos',
    thumbnailUrl: 'https://img.youtube.com/vi/E3X7vjA1W2c/hqdefault.jpg',
  },
  {
    id: 'l-js-8',
    moduleId: 'mod-js',
    order: 8,
    title: 'Curso JavaScript #08 - Operadores Relacionais, Lógicos e Ternário',
    type: 'video',
    durationMin: 35,
    description: 'Comparações de igualdade estrita (===), operadores lógicos (&&, ||, !) e o operador ternário (?:).',
    videoId: 'vrP-_T-a62A',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlsK3Nr9GVvXCbpQyHQl1o1',
    technology: 'JavaScript',
    topic: 'Operadores Lógicos e Ternário',
    thumbnailUrl: 'https://img.youtube.com/vi/vrP-_T-a62A/hqdefault.jpg',
  },
  {
    id: 'l-js-9',
    moduleId: 'mod-js',
    order: 9,
    title: 'Curso JavaScript #09 - Introdução ao DOM (Document Object Model)',
    type: 'video',
    durationMin: 34,
    description: 'A árvore DOM: selecionando elementos HTML por TagName, ID, ClassName e querySelector.',
    videoId: 'WWZX8RWLxIk',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlsK3Nr9GVvXCbpQyHQl1o1',
    technology: 'JavaScript',
    topic: 'Árvore DOM',
    thumbnailUrl: 'https://img.youtube.com/vi/WWZX8RWLxIk/hqdefault.jpg',
  },
  {
    id: 'l-js-10',
    moduleId: 'mod-js',
    order: 10,
    title: 'Curso JavaScript #10 - Eventos DOM e Funções de Disparo',
    type: 'video',
    durationMin: 36,
    description: 'Ouvindo eventos do mouse e teclado com addEventListener e alterando estilos em tempo real.',
    videoId: 'wWnQH84EVBQ',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlsK3Nr9GVvXCbpQyHQl1o1',
    technology: 'JavaScript',
    topic: 'Eventos DOM',
    thumbnailUrl: 'https://img.youtube.com/vi/wWnQH84EVBQ/hqdefault.jpg',
  },
  {
    id: 'l-js-11',
    moduleId: 'mod-js',
    order: 11,
    title: 'Curso JavaScript #11 - Condições em JavaScript (if / else)',
    type: 'video',
    durationMin: 31,
    description: 'Tomada de decisões com estruturas condicionais simples, compostas e validação de regras de negócio.',
    videoId: 'cOD1l2nnNnU',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlsK3Nr9GVvXCbpQyHQl1o1',
    technology: 'JavaScript',
    topic: 'Condicionais if/else',
    thumbnailUrl: 'https://img.youtube.com/vi/cOD1l2nnNnU/hqdefault.jpg',
  },
  {
    id: 'l-js-12',
    moduleId: 'mod-js',
    order: 12,
    title: 'Curso JavaScript #12 - Condições Aninhadas e Múltiplas (switch / case)',
    type: 'video',
    durationMin: 33,
    description: 'Condições aninhadas para horas do dia, voto obrigatório e seleção múltipla com switch case.',
    videoId: 'eeXvhcpnp1g',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlsK3Nr9GVvXCbpQyHQl1o1',
    technology: 'JavaScript',
    topic: 'Switch Case',
    thumbnailUrl: 'https://img.youtube.com/vi/eeXvhcpnp1g/hqdefault.jpg',
  },
  {
    id: 'l-js-13',
    moduleId: 'mod-js',
    order: 13,
    title: 'Curso JavaScript #13 - Estruturas de Repetição (while / do while)',
    type: 'video',
    durationMin: 30,
    description: 'Laços de repetição com teste no início e no final para automatização de tarefas.',
    videoId: '5rZqYPKIwkY',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlsK3Nr9GVvXCbpQyHQl1o1',
    technology: 'JavaScript',
    topic: 'Loops while',
    thumbnailUrl: 'https://img.youtube.com/vi/5rZqYPKIwkY/hqdefault.jpg',
  },
  {
    id: 'l-js-14',
    moduleId: 'mod-js',
    order: 14,
    title: 'Curso JavaScript #14 - Estrutura de Repetição com Variável de Controle (for)',
    type: 'video',
    durationMin: 32,
    description: 'O laço for tradicional, inicialização, teste lógico e incremento para percorrer sequências.',
    videoId: 'eX-lkN_fZfc',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlsK3Nr9GVvXCbpQyHQl1o1',
    technology: 'JavaScript',
    topic: 'Laço for',
    thumbnailUrl: 'https://img.youtube.com/vi/eX-lkN_fZfc/hqdefault.jpg',
  },
  {
    id: 'l-js-15',
    moduleId: 'mod-js',
    order: 15,
    title: 'Curso JavaScript #15 - Variáveis Compostas (Arrays / Vetores em JS)',
    type: 'video',
    durationMin: 35,
    description: 'Criação de arrays, índices, métodos push, length, sort e iteração com laços for..in e for..of.',
    videoId: 'XdkW62tkbA4',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlsK3Nr9GVvXCbpQyHQl1o1',
    technology: 'JavaScript',
    topic: 'Arrays e Métodos',
    thumbnailUrl: 'https://img.youtube.com/vi/XdkW62tkbA4/hqdefault.jpg',
  },
  {
    id: 'l-js-16',
    moduleId: 'mod-js',
    order: 16,
    title: 'Curso JavaScript #16 - Funções em JavaScript (Parâmetros e Retorno)',
    type: 'video',
    durationMin: 38,
    description: 'Declaração de funções, passagem de parâmetros formais e reais, retorno de valores e funções recursivas.',
    videoId: 'mc3TKp2XzhI',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dlsK3Nr9GVvXCbpQyHQl1o1',
    technology: 'JavaScript',
    topic: 'Funções e Parâmetros',
    thumbnailUrl: 'https://img.youtube.com/vi/mc3TKp2XzhI/hqdefault.jpg',
  },

  // --- Módulo 7: React & TypeScript (8 Aulas Sequenciais) ---
  {
    id: 'l-react-1',
    moduleId: 'mod-react',
    order: 1,
    title: 'React 18 & TypeScript #01 - Introdução, JSX e Criando Projeto com Vite',
    type: 'video',
    durationMin: 35,
    description: 'A mentalidade de componentização reativa, arquitetura de SPAs e inicialização rápida de projetos com Vite.',
    videoId: 'ErjWNvP9mGQ',
    source: 'Matheus Battisti (Hora de Codar)',
    playlistId: 'PLnDvRpP8BnezptmknbFpvo_kofnpqVpU-',
    technology: 'React',
    topic: 'Componentes e JSX',
    thumbnailUrl: 'https://img.youtube.com/vi/ErjWNvP9mGQ/hqdefault.jpg',
  },
  {
    id: 'l-react-2',
    moduleId: 'mod-react',
    order: 2,
    title: 'React 18 & TypeScript #02 - Componentes Reutilizáveis e Renderização',
    type: 'video',
    durationMin: 36,
    description: 'Construção de componentes atômicos reutilizáveis e a árvore de componentes reativos.',
    videoId: 'dpw9nfndDpc',
    source: 'Rocketseat',
    technology: 'React',
    topic: 'Componentização',
    thumbnailUrl: 'https://img.youtube.com/vi/dpw9nfndDpc/hqdefault.jpg',
  },
  {
    id: 'l-react-3',
    moduleId: 'mod-react',
    order: 3,
    title: 'React 18 & TypeScript #03 - Props: Passagem de Propriedades e Tipagem Estrita',
    type: 'video',
    durationMin: 32,
    description: 'Passagem de dados unidirecional entre componentes pais e filhos com interfaces TypeScript.',
    videoId: 'x4r8U7W_3gA',
    source: 'Rocketseat',
    technology: 'React',
    topic: 'Props e TypeScript',
    thumbnailUrl: 'https://img.youtube.com/vi/x4r8U7W_3gA/hqdefault.jpg',
  },
  {
    id: 'l-react-4',
    moduleId: 'mod-react',
    order: 4,
    title: 'React 18 & TypeScript #04 - Gerenciamento de Estado Reativo com useState',
    type: 'video',
    durationMin: 38,
    description: 'Como o React controla a re-renderização de componentes através de variáveis de estado com o hook useState.',
    videoId: 'mc3TKp2XzhI',
    source: 'Matheus Battisti (Hora de Codar)',
    technology: 'React',
    topic: 'Hook useState',
    thumbnailUrl: 'https://img.youtube.com/vi/mc3TKp2XzhI/hqdefault.jpg',
  },
  {
    id: 'l-react-5',
    moduleId: 'mod-react',
    order: 5,
    title: 'React 18 & TypeScript #05 - Ciclo de Vida e Efeitos com useEffect',
    type: 'video',
    durationMin: 40,
    description: 'Efeitos colaterais, sincronização com APIs externas e arrays de dependências no useEffect.',
    videoId: 'WWZX8RWLxIk',
    source: 'Rocketseat',
    technology: 'React',
    topic: 'Hook useEffect',
    thumbnailUrl: 'https://img.youtube.com/vi/WWZX8RWLxIk/hqdefault.jpg',
  },
  {
    id: 'l-react-6',
    moduleId: 'mod-react',
    order: 6,
    title: 'React 18 & TypeScript #06 - Formulários Controlados e Validação de Inputs',
    type: 'video',
    durationMin: 34,
    description: 'Inputs controlados no React, manipulação de onChange e envio de dados com onSubmit.',
    videoId: '1-w1RfGiov4',
    source: 'Matheus Battisti (Hora de Codar)',
    technology: 'React',
    topic: 'Formulários Controlados',
    thumbnailUrl: 'https://img.youtube.com/vi/1-w1RfGiov4/hqdefault.jpg',
  },
  {
    id: 'l-react-7',
    moduleId: 'mod-react',
    order: 7,
    title: 'React 18 & TypeScript #07 - React Router DOM: Rotas e Páginas em SPAs',
    type: 'video',
    durationMin: 36,
    description: 'Criando navegação multi-páginas no cliente com BrowserRouter, Routes, Route e Link.',
    videoId: '8mei6XYRhR4',
    source: 'Matheus Battisti (Hora de Codar)',
    technology: 'React',
    topic: 'React Router DOM',
    thumbnailUrl: 'https://img.youtube.com/vi/8mei6XYRhR4/hqdefault.jpg',
  },
  {
    id: 'l-react-8',
    moduleId: 'mod-react',
    order: 8,
    title: 'React 18 & TypeScript #08 - Custom Hooks e Boas Práticas de Organização',
    type: 'video',
    durationMin: 35,
    description: 'Encapsulando lógica reutilizável em hooks customizados e padrões modernos de arquitetura front-end.',
    videoId: 'XdkW62tkbA4',
    source: 'Rocketseat',
    technology: 'React',
    topic: 'Custom Hooks',
    thumbnailUrl: 'https://img.youtube.com/vi/XdkW62tkbA4/hqdefault.jpg',
  },

  // --- Módulo 8: Node.js, Express & APIs RESTful (8 Aulas Sequenciais) ---
  {
    id: 'l-node-1',
    moduleId: 'mod-node',
    order: 1,
    title: 'Node.js & Express #01 - Introdução ao Node.js, V8 e Event Loop',
    type: 'video',
    durationMin: 36,
    description: 'O runtime Node.js no backend, arquitetura assíncrona não-bloqueante e gerenciamento de pacotes com NPM.',
    videoId: 'FMhScnY0dME',
    source: 'Rocketseat',
    technology: 'Node.js & APIs',
    topic: 'Node.js Fundamentals',
    thumbnailUrl: 'https://img.youtube.com/vi/FMhScnY0dME/hqdefault.jpg',
  },
  {
    id: 'l-node-2',
    moduleId: 'mod-node',
    order: 2,
    title: 'Node.js & Express #02 - Criando Servidores HTTP e APIs com Express',
    type: 'video',
    durationMin: 40,
    description: 'Rotas, requisições GET/POST/PUT/DELETE, express.json() e respostas estruturadas em JSON.',
    videoId: 'G3e-cpL7ofc',
    source: 'Rocketseat',
    technology: 'Node.js & APIs',
    topic: 'Express HTTP',
    thumbnailUrl: 'https://img.youtube.com/vi/G3e-cpL7ofc/hqdefault.jpg',
  },
  {
    id: 'l-node-3',
    moduleId: 'mod-node',
    order: 3,
    title: 'Node.js & Express #03 - Métodos HTTP e Parâmetros (Route, Query e Body Params)',
    type: 'video',
    durationMin: 32,
    description: 'Diferença entre parâmetros de rota (:id), query strings (?page=1) e corpo da requisição (req.body).',
    videoId: '8mei6XYRhR4',
    source: 'Rocketseat',
    technology: 'Node.js & APIs',
    topic: 'Parâmetros HTTP',
    thumbnailUrl: 'https://img.youtube.com/vi/8mei6XYRhR4/hqdefault.jpg',
  },
  {
    id: 'l-node-4',
    moduleId: 'mod-node',
    order: 4,
    title: 'Node.js & Express #04 - Middlewares: Interceptadores e Validações',
    type: 'video',
    durationMin: 35,
    description: 'Uso de middlewares globais e por rota para logging, validação de cabeçalhos e tratamento centralizado de erros.',
    videoId: 'WWZX8RWLxIk',
    source: 'Rocketseat',
    technology: 'Node.js & APIs',
    topic: 'Middlewares',
    thumbnailUrl: 'https://img.youtube.com/vi/WWZX8RWLxIk/hqdefault.jpg',
  },
  {
    id: 'l-node-5',
    moduleId: 'mod-node',
    order: 5,
    title: 'Node.js & Express #05 - Arquitetura MVC: Controllers, Services e Rotas',
    type: 'video',
    durationMin: 38,
    description: 'Organizando regras de negócio desacopladas e dividindo o código em camadas profissionais.',
    videoId: '1-w1RfGiov4',
    source: 'Rocketseat',
    technology: 'Node.js & APIs',
    topic: 'Arquitetura MVC',
    thumbnailUrl: 'https://img.youtube.com/vi/1-w1RfGiov4/hqdefault.jpg',
  },
  {
    id: 'l-node-6',
    moduleId: 'mod-node',
    order: 6,
    title: 'Node.js & Express #06 - Autenticação com JSON Web Tokens (JWT) e Bcrypt',
    type: 'video',
    durationMin: 42,
    description: 'Hashing seguro de senhas com bcryptjs, geração de tokens JWT e proteção de rotas privadas.',
    videoId: 'XdkW62tkbA4',
    source: 'Rocketseat',
    technology: 'Node.js & APIs',
    topic: 'Autenticação JWT',
    thumbnailUrl: 'https://img.youtube.com/vi/XdkW62tkbA4/hqdefault.jpg',
  },
  {
    id: 'l-node-7',
    moduleId: 'mod-node',
    order: 7,
    title: 'Node.js & Express #07 - Upload de Arquivos e Variáveis de Ambiente (.env)',
    type: 'video',
    durationMin: 34,
    description: 'Gerenciamento de credenciais com dotenv e processamento de uploads multipart/form-data com Multer.',
    videoId: 'mc3TKp2XzhI',
    source: 'Rocketseat',
    technology: 'Node.js & APIs',
    topic: 'Uploads e Env',
    thumbnailUrl: 'https://img.youtube.com/vi/mc3TKp2XzhI/hqdefault.jpg',
  },
  {
    id: 'l-node-8',
    moduleId: 'mod-node',
    order: 8,
    title: 'Node.js & Express #08 - Documentação com Swagger e Testes Automatizados',
    type: 'video',
    durationMin: 36,
    description: 'Documentando endpoints REST com Swagger OpenAPI e escrevendo testes de integração com Jest e Supertest.',
    videoId: 'ErjWNvP9mGQ',
    source: 'Rocketseat',
    technology: 'Node.js & APIs',
    topic: 'Swagger e Testes',
    thumbnailUrl: 'https://img.youtube.com/vi/ErjWNvP9mGQ/hqdefault.jpg',
  },

  // --- Módulo 9: Bancos de Dados & SQL (Curso em Vídeo MySQL - 10 Aulas Sequenciais) ---
  {
    id: 'l-db-1',
    moduleId: 'mod-db',
    order: 1,
    title: 'Curso de MySQL #01 - O que é um Banco de Dados Relacional?',
    type: 'video',
    durationMin: 35,
    description: 'Tabelas, linhas, colunas, chaves primárias e os fundamentos do modelo relacional.',
    videoId: 'Ofktsne-utM',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dkBs-795DdVwg6rqVU14o6t',
    technology: 'SQL',
    topic: 'Modelagem Relacional',
    thumbnailUrl: 'https://img.youtube.com/vi/Ofktsne-utM/hqdefault.jpg',
  },
  {
    id: 'l-db-2',
    moduleId: 'mod-db',
    order: 2,
    title: 'Curso de MySQL #02 - Instalando MySQL Server e MySQL Workbench',
    type: 'video',
    durationMin: 28,
    description: 'Instalação do SGBD MySQL, conexão local e primeiros passos no Workbench.',
    videoId: 'Cz3_f5j_7s4',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dkBs-795DdVwg6rqVU14o6t',
    technology: 'SQL',
    topic: 'Instalação SGBD',
    thumbnailUrl: 'https://img.youtube.com/vi/Cz3_f5j_7s4/hqdefault.jpg',
  },
  {
    id: 'l-db-3',
    moduleId: 'mod-db',
    order: 3,
    title: 'Curso de MySQL #03 - Criando o Primeiro Banco e Tabelas (CREATE)',
    type: 'video',
    durationMin: 32,
    description: 'Comandos CREATE DATABASE e CREATE TABLE com definição estrita de tipos de dados primitivos.',
    videoId: 'fP49L1AM5TE',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dkBs-795DdVwg6rqVU14o6t',
    technology: 'SQL',
    topic: 'CREATE TABLE',
    thumbnailUrl: 'https://img.youtube.com/vi/fP49L1AM5TE/hqdefault.jpg',
  },
  {
    id: 'l-db-4',
    moduleId: 'mod-db',
    order: 4,
    title: 'Curso de MySQL #04 - Inserindo Dados na Tabela (INSERT INTO)',
    type: 'video',
    durationMin: 30,
    description: 'Inserção de múltiplos registros com INSERT INTO e valores padrão DEFAULT.',
    videoId: '8yptZ1N_j0U',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dkBs-795DdVwg6rqVU14o6t',
    technology: 'SQL',
    topic: 'INSERT INTO',
    thumbnailUrl: 'https://img.youtube.com/vi/8yptZ1N_j0U/hqdefault.jpg',
  },
  {
    id: 'l-db-5',
    moduleId: 'mod-db',
    order: 5,
    title: 'Curso de MySQL #05 - Alterando a Estrutura da Tabela (ALTER TABLE)',
    type: 'video',
    durationMin: 28,
    description: 'Adicionando e modificando colunas com ALTER TABLE, ADD COLUMN, MODIFY e DROP COLUMN.',
    videoId: 'f26mEZ5eD9k',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dkBs-795DdVwg6rqVU14o6t',
    technology: 'SQL',
    topic: 'ALTER TABLE',
    thumbnailUrl: 'https://img.youtube.com/vi/f26mEZ5eD9k/hqdefault.jpg',
  },
  {
    id: 'l-db-6',
    moduleId: 'mod-db',
    order: 6,
    title: 'Curso de MySQL #06 - Manipulando Linhas (UPDATE, DELETE e TRUNCATE)',
    type: 'video',
    durationMin: 33,
    description: 'Atualização e exclusão atômica de registros com cláusula WHERE de segurança.',
    videoId: 'ZzaMmBwtWj0',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dkBs-795DdVwg6rqVU14o6t',
    technology: 'SQL',
    topic: 'UPDATE e DELETE',
    thumbnailUrl: 'https://img.youtube.com/vi/ZzaMmBwtWj0/hqdefault.jpg',
  },
  {
    id: 'l-db-7',
    moduleId: 'mod-db',
    order: 7,
    title: 'Curso de MySQL #07 - Consultas Básicas com SELECT (WHERE, ORDER BY, LIKE)',
    type: 'video',
    durationMin: 36,
    description: 'Filtrando resultados com WHERE, operadores lógicos, ordenação ASC/DESC e buscas com LIKE.',
    videoId: 'pyd_k_33R1k',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dkBs-795DdVwg6rqVU14o6t',
    technology: 'SQL',
    topic: 'SELECT & WHERE',
    thumbnailUrl: 'https://img.youtube.com/vi/pyd_k_33R1k/hqdefault.jpg',
  },
  {
    id: 'l-db-8',
    moduleId: 'mod-db',
    order: 8,
    title: 'Curso de MySQL #08 - Agregações: COUNT, SUM, AVG, GROUP BY e HAVING',
    type: 'video',
    durationMin: 38,
    description: 'Funções de agrupamento, contagem e filtros avançados em relatórios estatísticos com HAVING.',
    videoId: 'Y4QG_Y9K5j4',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dkBs-795DdVwg6rqVU14o6t',
    technology: 'SQL',
    topic: 'GROUP BY e Agregações',
    thumbnailUrl: 'https://img.youtube.com/vi/Y4QG_Y9K5j4/hqdefault.jpg',
  },
  {
    id: 'l-db-9',
    moduleId: 'mod-db',
    order: 9,
    title: 'Curso de MySQL #09 - Chaves Estrangeiras e Relacionamentos (FOREIGN KEY)',
    type: 'video',
    durationMin: 35,
    description: 'Relacionamentos 1:1, 1:N e N:N com constraints de integridade referencial FOREIGN KEY.',
    videoId: 'J2E2n5L0zB0',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dkBs-795DdVwg6rqVU14o6t',
    technology: 'SQL',
    topic: 'Chaves Estrangeiras',
    thumbnailUrl: 'https://img.youtube.com/vi/J2E2n5L0zB0/hqdefault.jpg',
  },
  {
    id: 'l-db-10',
    moduleId: 'mod-db',
    order: 10,
    title: 'Curso de MySQL #10 - Junção de Tabelas com INNER JOIN e LEFT JOIN',
    type: 'video',
    durationMin: 40,
    description: 'Consultando múltiplas tabelas simultaneamente com INNER JOIN, LEFT JOIN e RIGHT JOIN.',
    videoId: 'y0A5V9V01K8',
    source: 'Curso em Vídeo (Gustavo Guanabara)',
    playlistId: 'PLHz_AreHm4dkBs-795DdVwg6rqVU14o6t',
    technology: 'SQL',
    topic: 'INNER JOIN',
    thumbnailUrl: 'https://img.youtube.com/vi/y0A5V9V01K8/hqdefault.jpg',
  },

  // --- Módulo 10: Full Stack Integration & Deploy (4 Aulas Sequenciais) ---
  {
    id: 'l-fs-1',
    moduleId: 'mod-fullstack',
    order: 1,
    title: 'Full Stack #01 - Arquitetura de Aplicação Completa Ponta a Ponta',
    type: 'video',
    durationMin: 45,
    description: 'Estruturação de um projeto monorepo ou client/server com React no Front-end e Node.js no Back-end.',
    videoId: 'L1bfXp1fL4w',
    source: 'Rocketseat',
    technology: 'Full Stack',
    topic: 'Arquitetura Full Stack',
    thumbnailUrl: 'https://img.youtube.com/vi/L1bfXp1fL4w/hqdefault.jpg',
  },
  {
    id: 'l-fs-2',
    moduleId: 'mod-fullstack',
    order: 2,
    title: 'Full Stack #02 - Conectando o Front-end ao Back-end via Axios e CORS',
    type: 'video',
    durationMin: 38,
    description: 'Consumindo endpoints RESTful a partir do React, tratamento de CORS e interceptadores de autenticação.',
    videoId: 'xEKo29OWOPQ',
    source: 'Rocketseat',
    technology: 'Full Stack',
    topic: 'Axios e Conexão HTTP',
    thumbnailUrl: 'https://img.youtube.com/vi/xEKo29OWOPQ/hqdefault.jpg',
  },
  {
    id: 'l-fs-3',
    moduleId: 'mod-fullstack',
    order: 3,
    title: 'Full Stack #03 - Integração com Banco de Dados em Produção (Supabase / Prisma)',
    type: 'video',
    durationMin: 42,
    description: 'Modelagem e migrações no Prisma ORM e conexão com instâncias gerenciadas do PostgreSQL.',
    videoId: 'Ofktsne-utM',
    source: 'Rocketseat',
    technology: 'Full Stack',
    topic: 'Banco em Nuvem',
    thumbnailUrl: 'https://img.youtube.com/vi/Ofktsne-utM/hqdefault.jpg',
  },
  {
    id: 'l-fs-4',
    moduleId: 'mod-fullstack',
    order: 4,
    title: 'Full Stack #04 - Pipeline de Deploy: Vercel (Front) e Render (Back)',
    type: 'video',
    durationMin: 40,
    description: 'Configuração de variáveis de ambiente em produção, esteira de CI/CD automática e publicação ao vivo.',
    videoId: 'jgQjeqU-viU',
    source: 'Rocketseat',
    technology: 'Full Stack',
    topic: 'Deploy e CI/CD',
    thumbnailUrl: 'https://img.youtube.com/vi/jgQjeqU-viU/hqdefault.jpg',
  },

  // --- Módulo 11: Carreira Tech & Entrevistas (3 Aulas Sequenciais) ---
  {
    id: 'l-carreira-1',
    moduleId: 'mod-carreira',
    order: 1,
    title: 'Carreira Tech #01 - Construindo um Portfólio no GitHub que se Destaca',
    type: 'video',
    durationMin: 30,
    description: 'Como apresentar projetos reais, estruturar READMEs profissionais e documentar código para recrutadores.',
    videoId: '1sDssGvO790',
    source: 'Rocketseat',
    technology: 'Carreira Tech',
    topic: 'Portfólio GitHub',
    thumbnailUrl: 'https://img.youtube.com/vi/1sDssGvO790/hqdefault.jpg',
  },
  {
    id: 'l-carreira-2',
    moduleId: 'mod-carreira',
    order: 2,
    title: 'Carreira Tech #02 - Otimização de LinkedIn e Currículo para Vagas Tech',
    type: 'video',
    durationMin: 28,
    description: 'Palavras-chave, posicionamento estratégico e networking para atrair propostas de emprego.',
    videoId: '1-w1RfGiov4',
    source: 'Rocketseat',
    technology: 'Carreira Tech',
    topic: 'LinkedIn e Currículo',
    thumbnailUrl: 'https://img.youtube.com/vi/1-w1RfGiov4/hqdefault.jpg',
  },
  {
    id: 'l-carreira-3',
    moduleId: 'mod-carreira',
    order: 3,
    title: 'Carreira Tech #03 - Como Vencer em Entrevistas Técnicas e Live Coding',
    type: 'video',
    durationMin: 35,
    description: 'Dicas práticas para se sair bem em desafios de programação ao vivo, resolução de algoritmos e perguntas comportamentais.',
    videoId: 'BXqUH86F-5Y',
    source: 'Rocketseat',
    technology: 'Carreira Tech',
    topic: 'Entrevistas e Live Coding',
    thumbnailUrl: 'https://img.youtube.com/vi/BXqUH86F-5Y/hqdefault.jpg',
  },
]

export const mockLessons: Lesson[] = []

export const defaultOfficialLessons: Lesson[] = rawLessons.map((l) => ({
  ...l,
  externalVideoId: l.externalVideoId || l.videoId,
  videoUrl: l.videoUrl || (l.videoId ? `https://www.youtube.com/watch?v=${l.videoId}` : undefined),
  sourceType: l.sourceType || (l.type === 'video' ? 'youtube' : 'external'),
  availabilityStatus: l.availabilityStatus || 'available',
  youtubeExists: l.youtubeExists ?? true,
  embedAvailable: l.embedAvailable ?? true,
  lastCheckedAt: l.lastCheckedAt || new Date().toISOString(),
}))

export const defaultCourses: Course[] = []

export const defaultOfficialCourses: Course[] = [
  {
    id: 'crs-logica',
    title: 'Curso de Algoritmos & Lógica de Programação',
    slug: 'logica-de-programacao-algoritmos',
    description: 'O curso de referência absoluta de Gustavo Guanabara (Curso em Vídeo) para aprender a programar do zero com 17 aulas práticas completas.',
    level: 'iniciante-absoluto',
    technology: 'Lógica & Algoritmos',
    category: 'Fundamentos da Programação',
    thumbnailUrl: 'https://img.youtube.com/vi/8mei6XYRhR4/hqdefault.jpg',
    status: 'ativo',
    playlistId: 'PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV',
    playlistUrl: 'https://www.youtube.com/playlist?list=PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV',
    channelTitle: 'Curso em Vídeo',
    classificationConfidence: 100,
    prerequisites: [],
    skills: ['Lógica de Programação', 'Algoritmos', 'Visualg', 'Estruturas Condicionais', 'Estruturas de Repetição', 'Procedimentos', 'Funções', 'Vetores', 'Matrizes'],
    modulesCount: 1,
    lessonsCount: 17,
    totalHours: 12,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'crs-algoritmos',
    title: 'Curso de Algoritmos e Estruturas de Dados',
    slug: 'curso-algoritmos-estruturas-de-dados',
    description: 'Fundamentos de complexidade de código (Big O), manipulação de memória com matrizes, filas, pilhas e algoritmos de busca.',
    level: 'iniciante',
    technology: 'Lógica & Algoritmos',
    category: 'Fundamentos da Programação',
    thumbnailUrl: 'https://img.youtube.com/vi/RkWpd_e5W44/hqdefault.jpg',
    status: 'ativo',
    channelTitle: 'DevMedia & Código Fonte TV',
    classificationConfidence: 96,
    prerequisites: ['mod-logica'],
    skills: ['Algoritmos', 'Complexidade Big-O', 'Estruturas de Dados', 'Pilhas e Filas', 'Ordenação'],
    modulesCount: 1,
    lessonsCount: 5,
    totalHours: 8,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'crs-git',
    title: 'Curso de Git e GitHub Profissional',
    slug: 'curso-git-e-github',
    description: 'Domine o controle de versão de software com commits atômicos, histórico, chaves SSH, branches e resolução de conflitos de merge.',
    level: 'iniciante',
    technology: 'Git & GitHub',
    category: 'Fundamentos da Programação',
    thumbnailUrl: 'https://img.youtube.com/vi/6Czd1Yetaac/hqdefault.jpg',
    status: 'ativo',
    playlistId: 'PLHz_AreHm4dm7ZULPAmadvjNdH6zkzpN1',
    playlistUrl: 'https://www.youtube.com/playlist?list=PLHz_AreHm4dm7ZULPAmadvjNdH6zkzpN1',
    channelTitle: 'Curso em Vídeo',
    classificationConfidence: 98,
    prerequisites: ['mod-algoritmos'],
    skills: ['Git', 'GitHub', 'Versionamento', 'Branches', 'Pull Requests', 'SSH'],
    modulesCount: 1,
    lessonsCount: 8,
    totalHours: 6,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'crs-html',
    title: 'Curso de HTML5 Semântico & Estruturação Web',
    slug: 'curso-html5-semantico',
    description: 'Construa páginas web semânticas, acessíveis e otimizadas para SEO com 10 aulas completas de HTML5.',
    level: 'iniciante-absoluto',
    technology: 'HTML5 & CSS3',
    category: 'Web & Front-end',
    thumbnailUrl: 'https://img.youtube.com/vi/jgQjeqU-viU/hqdefault.jpg',
    status: 'ativo',
    playlistId: 'PLHz_AreHm4dlAnJ_jJtV29RFxnPHDuk9o',
    playlistUrl: 'https://www.youtube.com/playlist?list=PLHz_AreHm4dlAnJ_jJtV29RFxnPHDuk9o',
    channelTitle: 'Curso em Vídeo',
    classificationConfidence: 99,
    prerequisites: ['mod-git'],
    skills: ['HTML5', 'Semântica Web', 'SEO', 'Acessibilidade', 'Formulários', 'Links'],
    modulesCount: 1,
    lessonsCount: 10,
    totalHours: 10,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'crs-css',
    title: 'Curso de CSS3, Flexbox & CSS Grid',
    slug: 'curso-css3-flexbox-grid',
    description: 'Estilização moderna, modelo de caixas (Box Model), Flexbox, CSS Grid, responsividade e design Mobile-First.',
    level: 'iniciante',
    technology: 'HTML5 & CSS3',
    category: 'Web & Front-end',
    thumbnailUrl: 'https://img.youtube.com/vi/vMlR8Fk_xU0/hqdefault.jpg',
    status: 'ativo',
    playlistId: 'PLHz_AreHm4dlAnJ_jJtV29RFxnPHDuk9o',
    playlistUrl: 'https://www.youtube.com/playlist?list=PLHz_AreHm4dlAnJ_jJtV29RFxnPHDuk9o',
    channelTitle: 'Curso em Vídeo & Origamid',
    classificationConfidence: 98,
    prerequisites: ['mod-html'],
    skills: ['CSS3', 'Box Model', 'Flexbox', 'CSS Grid', 'Design Responsivo', 'Mobile-First'],
    modulesCount: 1,
    lessonsCount: 8,
    totalHours: 12,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'crs-js',
    title: 'Curso de JavaScript Moderno (ES6+) & DOM',
    slug: 'curso-javascript-moderno',
    description: 'O curso definitivo de JavaScript por Gustavo Guanabara: variáveis, template strings, operadores, DOM, eventos, loops, arrays e funções.',
    level: 'iniciante',
    technology: 'JavaScript',
    category: 'Web & Front-end',
    thumbnailUrl: 'https://img.youtube.com/vi/BXqUH86F-5Y/hqdefault.jpg',
    status: 'ativo',
    playlistId: 'PLHz_AreHm4dlsK3Nr9GVvXCbpQyHQl1o1',
    playlistUrl: 'https://www.youtube.com/playlist?list=PLHz_AreHm4dlsK3Nr9GVvXCbpQyHQl1o1',
    channelTitle: 'Curso em Vídeo',
    classificationConfidence: 100,
    prerequisites: ['mod-css'],
    skills: ['JavaScript', 'ES6+', 'DOM', 'Eventos', 'Condicionais', 'Loops', 'Arrays', 'Funções'],
    modulesCount: 1,
    lessonsCount: 16,
    totalHours: 18,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'crs-react',
    title: 'Curso de React 18 & TypeScript',
    slug: 'curso-react-typescript',
    description: 'Desenvolvimento de SPAs escaláveis, componentes reutilizáveis, Props, Hooks (useState, useEffect) e React Router DOM.',
    level: 'intermediario',
    technology: 'React',
    category: 'Front-end Moderno',
    thumbnailUrl: 'https://img.youtube.com/vi/ErjWNvP9mGQ/hqdefault.jpg',
    status: 'ativo',
    playlistId: 'PLnDvRpP8BnezptmknbFpvo_kofnpqVpU-',
    playlistUrl: 'https://www.youtube.com/playlist?list=PLnDvRpP8BnezptmknbFpvo_kofnpqVpU-',
    channelTitle: 'Matheus Battisti (Hora de Codar)',
    classificationConfidence: 95,
    prerequisites: ['mod-js'],
    skills: ['React', 'TypeScript', 'JSX', 'Hooks', 'State', 'SPA', 'Router'],
    modulesCount: 1,
    lessonsCount: 8,
    totalHours: 16,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'crs-node',
    title: 'Curso de Node.js, Express & APIs RESTful',
    slug: 'curso-nodejs-express-apis',
    description: 'Servidores HTTP em Node.js, rotas, middlewares, controllers, arquitetura MVC, JWT e Swagger.',
    level: 'intermediario',
    technology: 'Node.js & APIs',
    category: 'Back-end',
    thumbnailUrl: 'https://img.youtube.com/vi/FMhScnY0dME/hqdefault.jpg',
    status: 'ativo',
    channelTitle: 'Rocketseat',
    classificationConfidence: 95,
    prerequisites: ['mod-js'],
    skills: ['Node.js', 'Express', 'APIs REST', 'Middlewares', 'JWT', 'MVC', 'Bcrypt'],
    modulesCount: 1,
    lessonsCount: 8,
    totalHours: 16,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'crs-db',
    title: 'Curso de Bancos de Dados & SQL (MySQL)',
    slug: 'curso-banco-de-dados-sql-mysql',
    description: 'Modelagem relacional completa, comandos CREATE, INSERT, UPDATE, DELETE, consultas com SELECT, JOINs e chaves estrangeiras.',
    level: 'iniciante',
    technology: 'SQL',
    category: 'Back-end',
    thumbnailUrl: 'https://img.youtube.com/vi/Ofktsne-utM/hqdefault.jpg',
    status: 'ativo',
    playlistId: 'PLHz_AreHm4dkBs-795DdVwg6rqVU14o6t',
    playlistUrl: 'https://www.youtube.com/playlist?list=PLHz_AreHm4dkBs-795DdVwg6rqVU14o6t',
    channelTitle: 'Curso em Vídeo',
    classificationConfidence: 99,
    prerequisites: ['mod-node'],
    skills: ['SQL', 'MySQL', 'Modelagem Relacional', 'CRUD', 'SELECT', 'JOINs', 'FOREIGN KEY'],
    modulesCount: 1,
    lessonsCount: 10,
    totalHours: 14,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'crs-fullstack',
    title: 'Curso de Projeto Full Stack & Deploy na Nuvem',
    slug: 'curso-projeto-full-stack-deploy',
    description: 'Integração completa de front-end React, back-end Node.js e banco de dados PostgreSQL com deploy no Vercel e Render.',
    level: 'intermediario',
    technology: 'Full Stack',
    category: 'Full Stack',
    thumbnailUrl: 'https://img.youtube.com/vi/L1bfXp1fL4w/hqdefault.jpg',
    status: 'ativo',
    channelTitle: 'Rocketseat',
    classificationConfidence: 95,
    prerequisites: ['mod-db'],
    skills: ['Full Stack', 'Axios', 'Prisma ORM', 'Deploy', 'Vercel', 'Render', 'CI/CD'],
    modulesCount: 1,
    lessonsCount: 4,
    totalHours: 18,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'crs-carreira',
    title: 'Curso de Preparação Profissional & Entrevistas Tech',
    slug: 'curso-preparacao-profissional-entrevistas',
    description: 'Como construir um portfólio no GitHub que chama a atenção de recrutadores, LinkedIn otimizado e estratégias para passar no live coding.',
    level: 'intermediario',
    technology: 'Carreira Tech',
    category: 'Carreira',
    thumbnailUrl: 'https://img.youtube.com/vi/1sDssGvO790/hqdefault.jpg',
    status: 'ativo',
    channelTitle: 'Rocketseat',
    classificationConfidence: 95,
    prerequisites: ['mod-fullstack'],
    skills: ['Portfólio no GitHub', 'Currículo Tech', 'LinkedIn', 'Entrevistas Técnicas', 'Live Coding'],
    modulesCount: 1,
    lessonsCount: 3,
    totalHours: 8,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'crs-python',
    title: 'Curso de Python 3 — Fundamentos',
    slug: 'curso-python-3-fundamentos',
    description: 'Curso completo de Python 3 por Gustavo Guanabara: sintaxe limpa, estruturas de controle e manipulação de dados.',
    level: 'iniciante',
    technology: 'Python',
    category: 'Backend & Automação',
    thumbnailUrl: 'https://img.youtube.com/vi/S9uPNppGsGo/hqdefault.jpg',
    status: 'ativo',
    playlistId: 'PLHz_AreHm4dlKP6QQCekuIPky1CiwmdI6',
    playlistUrl: 'https://www.youtube.com/playlist?list=PLHz_AreHm4dlKP6QQCekuIPky1CiwmdI6',
    channelTitle: 'Curso em Vídeo',
    classificationConfidence: 100,
    prerequisites: ['mod-logica'],
    skills: ['Python 3', 'Sintaxe', 'Estruturas de Dados', 'Funções', 'Automação'],
    modulesCount: 1,
    lessonsCount: 15,
    totalHours: 14,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
]

export const defaultTechnologySources: TechnologySource[] = [
  {
    id: 'ts-logica',
    technology: 'Lógica de Programação',
    primaryPlaylistId: 'PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV',
    primaryPlaylistUrl: 'https://www.youtube.com/playlist?list=PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV',
    channelTitle: 'Curso em Vídeo',
    status: 'ativo',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'ts-algoritmos',
    technology: 'Algoritmos e Estruturas de Dados',
    channelTitle: 'DevMedia & Código Fonte TV',
    status: 'ativo',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'ts-git',
    technology: 'Git & GitHub',
    primaryPlaylistId: 'PLHz_AreHm4dm7ZULPAmadvjNdH6zkzpN1',
    primaryPlaylistUrl: 'https://www.youtube.com/playlist?list=PLHz_AreHm4dm7ZULPAmadvjNdH6zkzpN1',
    channelTitle: 'Curso em Vídeo',
    status: 'ativo',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'ts-html',
    technology: 'HTML5 & CSS3',
    primaryPlaylistId: 'PLHz_AreHm4dlAnJ_jJtV29RFxnPHDuk9o',
    primaryPlaylistUrl: 'https://www.youtube.com/playlist?list=PLHz_AreHm4dlAnJ_jJtV29RFxnPHDuk9o',
    channelTitle: 'Curso em Vídeo',
    status: 'ativo',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'ts-js',
    technology: 'JavaScript',
    primaryPlaylistId: 'PLHz_AreHm4dlsK3Nr9GVvXCbpQyHQl1o1',
    primaryPlaylistUrl: 'https://www.youtube.com/playlist?list=PLHz_AreHm4dlsK3Nr9GVvXCbpQyHQl1o1',
    channelTitle: 'Curso em Vídeo',
    status: 'ativo',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'ts-react',
    technology: 'React',
    primaryPlaylistId: 'PLnDvRpP8BnezptmknbFpvo_kofnpqVpU-',
    primaryPlaylistUrl: 'https://www.youtube.com/playlist?list=PLnDvRpP8BnezptmknbFpvo_kofnpqVpU-',
    channelTitle: 'Matheus Battisti (Hora de Codar)',
    status: 'ativo',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'ts-node',
    technology: 'Node.js & APIs',
    channelTitle: 'Rocketseat',
    status: 'ativo',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'ts-db',
    technology: 'SQL',
    primaryPlaylistId: 'PLHz_AreHm4dkBs-795DdVwg6rqVU14o6t',
    primaryPlaylistUrl: 'https://www.youtube.com/playlist?list=PLHz_AreHm4dkBs-795DdVwg6rqVU14o6t',
    channelTitle: 'Curso em Vídeo',
    status: 'ativo',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'ts-fullstack',
    technology: 'Full Stack',
    channelTitle: 'Rocketseat',
    status: 'ativo',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'ts-carreira',
    technology: 'Carreira Tech',
    channelTitle: 'Rocketseat',
    status: 'ativo',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'ts-python',
    technology: 'Python',
    primaryPlaylistId: 'PLHz_AreHm4dlKP6QQCekuIPky1CiwmdI6',
    primaryPlaylistUrl: 'https://www.youtube.com/playlist?list=PLHz_AreHm4dlKP6QQCekuIPky1CiwmdI6',
    channelTitle: 'Curso em Vídeo',
    status: 'ativo',
    updatedAt: '2025-01-01T00:00:00Z',
  },
]

export const mockExercises: Exercise[] = [
  {
    id: 'ex-1',
    moduleId: 'mod-logica',
    type: 'multiple-choice',
    prompt: 'Qual a principal característica de um algoritmo eficiente?',
    options: [
      'Executar em ordem lógica com passos bem definidos e finitos',
      'Utilizar o máximo de memória possível para acelerar o código',
      'Ser escrito diretamente em linguagem de máquina binária',
      'Não possuir condições de parada',
    ],
    correctIndex: 0,
    explanation:
      'Um algoritmo é uma sequência finita de passos claros e não ambíguos para resolver um determinado problema.',
    difficulty: 'facil',
    points: 20,
  },
  {
    id: 'ex-2',
    moduleId: 'mod-logica',
    type: 'code',
    prompt: 'Complete o código para declarar uma variável `idade` do tipo inteiro com valor 25:',
    codeStarter: '// Declare a variável abaixo:\nlet ',
    codeSolution: 'let idade = 25',
    explanation: 'Em JavaScript usamos let ou const para declarar variáveis.',
    difficulty: 'facil',
    points: 20,
  },
  {
    id: 'ex-3',
    moduleId: 'mod-js',
    type: 'multiple-choice',
    prompt: 'Qual método de array cria um novo array transformando cada elemento com uma função?',
    options: ['forEach()', 'map()', 'filter()', 'reduce()'],
    correctIndex: 1,
    explanation: 'O método map() aplica uma função em cada item e retorna um novo array transformado.',
    difficulty: 'medio',
    points: 30,
  },
  {
    id: 'ex-4',
    moduleId: 'mod-react',
    type: 'multiple-choice',
    prompt: 'Qual Hook é utilizado para gerenciar efeitos colaterais (como requisições HTTP) no React?',
    options: ['useMemo', 'useState', 'useEffect', 'useCallback'],
    correctIndex: 2,
    explanation: 'useEffect executa efeitos colaterais após a renderização do componente.',
    difficulty: 'medio',
    points: 30,
  },
]

export const mockAssessments: Assessment[] = [
  {
    id: 'eval-logica',
    moduleId: 'mod-logica',
    title: 'Avaliação Oficial de Lógica de Programação',
    minScore: 50,
    timeLimitMin: 20,
    questions: [
      {
        id: 'q-log-1',
        topic: 'Algoritmos & Raciocínio',
        prompt: 'Se x = 10 e y = 20, qual o resultado da expressão: (x < 15) E (y == 20)?',
        options: ['Verdadeiro', 'Falso', 'Indefinido', 'Erro de sintaxe'],
        correctIndex: 0,
        explanation: 'Ambas as condições são verdadeiras (10 < 15 é V, e 20 == 20 é V), logo V E V = V.',
      },
      {
        id: 'q-log-2',
        topic: 'Estruturas de Repetição',
        prompt: 'Quantas vezes o laço executa: para i de 1 até 5 faça ... fimpara?',
        options: ['4 vezes', '5 vezes', '6 vezes', 'Infinitas vezes'],
        correctIndex: 1,
        explanation: 'O laço itera com os valores i = 1, 2, 3, 4, 5 (totalizando 5 iterações).',
      },
      {
        id: 'q-log-3',
        topic: 'Variáveis e Tipos',
        prompt: 'Qual tipo de variável deve ser utilizado para armazenar o valor "verdadeiro" ou "falso"?',
        options: ['Inteiro', 'Real', 'Caractere', 'Booleano (Lógico)'],
        correctIndex: 3,
        explanation: 'O tipo booleano/lógico armazena apenas dois estados possíveis: true ou false.',
      },
    ],
  },
]

export const mockAssessment = mockAssessments[0]

export const mockProjects: ModuleProject[] = [
  {
    id: 'proj-logica',
    moduleId: 'mod-logica',
    title: 'Calculadora de Média e Aprovação Escolar',
    description: 'Desenvolva um algoritmo que receba 4 notas de um aluno, calcule a média ponderada e exiba se ele foi aprovado (média >= 7.0), em recuperação (5.0 a 6.9) ou reprovado (< 5.0).',
    requirements: [
      'Entrada de 4 notas decimais',
      'Validação para notas entre 0 e 10',
      'Cálculo correto da média aritmética',
      'Estrutura condicional para os 3 status possíveis',
    ],
  },
]

export const mockModuleProjects = mockProjects

export const placementQuestions = [
  {
    id: 'pq-1',
    topic: 'Lógica de Programação',
    prompt: 'Qual é o resultado de uma expressão condicional `(10 > 5) && (3 == 4)`?',
    options: ['true', 'false', 'undefined', 'null'],
    correctIndex: 1,
    explanation: 'A primeira parte é verdadeira (10 > 5), mas a segunda é falsa (3 == 4). No operador E (&&), ambas precisam ser verdadeiras.',
  },
  {
    id: 'pq-2',
    topic: 'JavaScript & Sintaxe',
    prompt: 'Qual palavra-chave no JavaScript moderno declara uma variável de escopo de bloco cujo valor pode ser alterado?',
    options: ['var', 'const', 'let', 'def'],
    correctIndex: 2,
    explanation: 'A palavra-chave `let` cria uma variável reatribuível com escopo de bloco.',
  },
  {
    id: 'pq-3',
    topic: 'HTML & CSS',
    prompt: 'Qual propriedade CSS é utilizada para criar um layout unidimensional flexível de itens?',
    options: ['display: grid', 'display: flex', 'float: left', 'position: absolute'],
    correctIndex: 1,
    explanation: '`display: flex` ativa o Flexbox, ideal para distribuição e alinhamento de elementos em uma dimensão (linha ou coluna).',
  },
  {
    id: 'pq-4',
    topic: 'Front-end & React',
    prompt: 'Qual hook do React é o principal mecanismo para adicionar estado reativo a um componente funcional?',
    options: ['useEffect', 'useMemo', 'useState', 'useRef'],
    correctIndex: 2,
    explanation: '`useState` declara uma variável de estado que causa re-renderização quando atualizada.',
  },
  {
    id: 'pq-5',
    topic: 'Back-end & Banco de Dados',
    prompt: 'Em SQL, qual comando é utilizado para filtrar registros em uma consulta `SELECT`?',
    options: ['ORDER BY', 'GROUP BY', 'WHERE', 'HAVING'],
    correctIndex: 2,
    explanation: 'A cláusula `WHERE` filtra os registros antes de qualquer agrupamento ou ordenação.',
  },
]

export const mockAchievements: Achievement[] = [
  {
    id: 'ach-1',
    title: 'Primeiro Passo',
    description: 'Concluiu sua primeira aula com sucesso.',
    icon: 'play',
    unlocked: false,
    xpReward: 50,
  },
  {
    id: 'ach-2',
    title: 'Mestre da Lógica',
    description: 'Aprovado com nota máxima na avaliação de Lógica.',
    icon: 'brain',
    unlocked: false,
    xpReward: 200,
  },
  {
    id: 'ach-3',
    title: 'Criador de Projetos',
    description: 'Entregou seu primeiro projeto prático no GitHub.',
    icon: 'code',
    unlocked: false,
    xpReward: 300,
  },
  {
    id: 'ach-4',
    title: 'Foco de Aço',
    description: 'Manteve 7 dias consecutivos de estudos.',
    icon: 'flame',
    unlocked: false,
    xpReward: 500,
  },
]
